### ISSUE TITLE
build.py Python versioncheck fails

### ISSUE THREAD

**Issue by DaCoolX** [ungoogled-software/ungoogled-chromium-windows#10]
Trying to run build.py fails
I have Python 3.7.4 for "All Users" installed under C:\Program Files\Python37
Env variable path starts with
`Path=C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;[...]`

Output is
`D:\ungoogled-software\ungoogled-chromium-windows>py build.py
Python 3.7.4
usage: build.py [-h] [--disable-ssl-verification] [--7z-path SEVENZ_PATH]
build.py: error: Could not detect Python 3 version from output:
`

**Comment by flawedworld** [comment]
I'm also getting this :/

**Comment by Eloston** [comment]
Please read https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2#issuecomment-533771215 for context. To reiterate the key point, please read the README **carefully**. Let me know if it is still unclear.

**Comment by jeffmendoza** [comment]
This is still an issue, the stderr -> stdout change is needed from #9

**Comment by Eloston** [comment]
@jeffmendoza I see, thanks for explaining.
