### ISSUE TITLE
Cross building on Linux / GitHub Actions

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-windows#108]
It would be good to have automated releases using GitHub Actions. I've looked into the Windows runner a little and sadly due to how virtual drives are arranged I think its impossible to compile Chromium. The C: drive contains [preinstalled software](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) which is taking up a lot of space. On Linux it would be easy to [remove unused toolchains and similar](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/3d55adb7831a2a770821270faaa8818c92a58cce/.github/actions/stage/index.ts#L47) but the working directory for the Windows runner is located on D: which only has ~8GB of free storage.

As such I think to automate releases its nessesarry to [cross compile on Linux](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/win_cross.md). I [started working](https://github.com/networkException/ungoogled-chromium-windows/commit/600e7fad67e0f4b5c6783f84d3ca7b9e81af318b) on retrieving the Windows toolchain already but I'm not familiar with writing build scripts myself.

CC @wchen342 @Nifury could you help here maybe?

**Comment by wchen342** [comment]
Have you managed to solve to runner time limit problem? Do you still intend to do multi-step building?

**Comment by networkException** [comment]
On public runners multi step building is still required sadly, jobs are limited to 6h

**Comment by Nifury** [comment]
```powershell
DriveLetter FriendlyName      FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining      Size
----------- ------------      -------------- --------- ------------ ----------------- -------------      ----
            System Reserved   NTFS           Fixed     Healthy      OK                    465.45 MB    500 MB
C           Windows           NTFS           Fixed     Healthy      OK                     90.57 GB 255.51 GB
D           Temporary Storage NTFS           Fixed     Healthy      OK                      12.2 GB     14 GB
A                             Unknown        Removable Healthy      Unknown                     0 B       0 B
```

It seems we can pull and build the repo on the C: drive. It has plenty of space left. Removing Android SDKs and .net gives another 6 GB. 
I've set up a test workflow, and will report back if it builds successfully.

**Comment by networkException** [comment]
Having artifacts this large is inevitable, you can set them to expire more quickly if thats a concern

**Comment by wchen342** [comment]
There is a maximum GBs of artifacts per repo but it's undocumented. I forgot where I found it but I think it can support about 3-4 jobs on Linux.

**Comment by Nifury** [comment]
https://github.com/Nifury/ungoogled-chromium-windows/actions/runs/1413169079
I think we can build Chromium on Windows, though it could take about a day to compile everything.

**Comment by networkException** [comment]
Ok great! I think I saw some outdated storage numbers then, they sure didn't mention that much free space on C:

The long compile times are unfortunate but a self hosted runner could help in the future

**Comment by Nifury** [comment]
https://github.com/Nifury/ungoogled-chromium-windows/blob/github_action/.github/workflows/main.yml

Confirmed that this works, but we also need to update `build.py` to interrupt and resume the building process. 

I could use some help improving the yml file.

**Comment by wchen342** [comment]
For future reference, is it possible for you to give a list of all Windows/VS components you need to copy from a Windows machine or download from MS (and their terms)?

**Comment by Nifury** [comment]
> For future reference, is it possible for you to give a list of all Windows/VS components you need to copy from a Windows machine or download from MS (and their terms)?

I think we just need the “Desktop development with C++” component and the “MFC/ATL support” sub-components for VS, according to https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md#visual-studio

**Comment by tomasz1986** [comment]
Just a quick question. Does this mean that the Windows binaries are now going to be uploaded to a different repository? The previous ones have been available at https://github.com/Nifury/ungoogled-chromium-binaries/releases, but I'm now seeing the newest release located in https://github.com/Nifury/ungoogled-chromium-windows/releases.

**Comment by tomasz1986** [comment]
Great! This means we should just wait for the compilation to complete, right? At the moment, the last release in https://github.com/ungoogled-software/ungoogled-chromium-binaries is from 2016 🙃.

**Comment by Nifury** [comment]
Oh it's not in the Releases section. 
https://ungoogled-software.github.io/ungoogled-chromium-binaries/
