### ISSUE TITLE
Cannot find mini_installer.exe

### ISSUE THREAD

**Issue by Real0ver** [ungoogled-software/ungoogled-chromium-windows#110]
`Traceback (most recent call last):
  File "C:\Users\Administrator\ungoogled-chromium-windows\package.py", line 66, in <module>
    main()
  File "C:\Users\Administrator\ungoogled-chromium-windows\package.py", line 48, in main
    shutil.copyfile('build/src/out/Default/mini_installer.exe',
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build/src/out/Default/mini_installer.exe'`

**Comment by networkException** [comment]
Are you certain that `py build.py` finished without errors? Python 3.10 is known to cause problems

**Comment by Real0ver** [comment]
> Are you certain that `py build.py` finished without errors? Python 3.10 is known to cause problems

It finished with errors. I tried this on Windows 11 RTM

**Comment by Real0ver** [comment]
> > Are you certain that `py build.py` finished without errors? Python 3.10 is known to cause problems
> 
> It finished with errors. I tried this on Windows 11 RTM

I tried with Python 3.9, It worked fine, thank you!

**Comment by infinitegame111** [comment]
I had this same problem and figured it out myself it appears to work just fine for me hope it works for you
