### ISSUE TITLE
Missing tags? Windows x64

### ISSUE THREAD

**Issue by ivbit** [ungoogled-software/ungoogled-chromium-windows#116]
As of Nov 29 2021 there are 2 new binary builds to download at https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/
95.0.4638.69-1 and 96.0.4664.45-1
However, the last tag at https://github.com/ungoogled-software/ungoogled-chromium-windows
is 95.0.4638.54-1.1
Are there tags missing for 95.0.4638.69-1 and 96.0.4664.45-1?
How can I build from source the 95.0.4638.69-1 and/or 96.0.4664.45-1?

**Comment by networkException** [comment]
The binaries page lists links to user submitted files, 96.0.4664.45 is https://github.com/Nifury/ungoogled-chromium-windows/releases/tag/96.0.4664.45 and 95.0.4638.69-1 is https://github.com/Nifury/ungoogled-chromium-windows/commit/9c970112aed31867c0d66fdcbd99d4e9f543c84e.
