### ISSUE TITLE
Passwords do not get saved

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [ungoogled-software/ungoogled-chromium-windows#128]
Describe the bug
I have enabled both options of the Autofill-Passwords feature. When I go to a site, enter my credentials and save them when the chrome save window pops up, it does not save them. In fact, if I click after that on the key icon while in the site, it says no password is saved on that site when I just did.

To Reproduce

Go to https://github.com/
Log in and save your information when the window appears on the page (assuming you have enabled both options in Autofill Passwords.
Click on the key icon and you will see that no passwords were saved.
Go to Settings-Autofill-Passwords and you will see no Github login information saved.
Expected behavior
The password should be saved and I could see it in the saved passwords in the settings.

Environment (please complete the following information):

OS/Platform and version: Windows 10 Pro 19044.1469
ungoogled-chromium version: Version 97.0.4692.99 (Official Build, ungoogled-chromium) (64-bit)

**Comment by rosman83** [comment]
Experiencing the same issue on the same platform. This is really a deal breaker for my productivity and making me consider switching to something else.

**Comment by PF4Public** [comment]
Fixed in 117
