### ISSUE TITLE
Build failing with ninja: fatal: unknown tool 'msvc'

### ISSUE THREAD

**Issue by Obaid51** [ungoogled-software/ungoogled-chromium-windows#138]
I have been trying to build ninja but getting this error when building this command
`C:\Users\-----\AppData\Local\Programs\Python\Python39\python.exe" "tools\gn\bootstrap\bootstrap.py" "-o" "out\Default\gn.exe" "--skip-generate-buildfiles"`
The error I am getting is 
`ninja: fatal: unknown tool 'msvc'`
I am using Windows 10 with Ninja 1.10.0
![build failed](https://user-images.githubusercontent.com/42531139/158741171-6e88690d-17b8-4187-855c-6f9a8ff9a918.JPG)

**Comment by kuoruan** [comment]
I got the same issue, how did you solved it?

**Comment by networkException** [comment]
This sounds like Visual Studio or one of the required components is not installed correctly
