### ISSUE TITLE
Repository maintenance

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-windows#144]
As is apparent from the month old #139 this repository is lacking proper maintenance, especially by windows users. For this reason we are looking into adding a new organisation team as described in https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/repo_management.md#teams-in-the-ungoogled-software-organization with access to this repository

@Nifury and @teeminus, I think you both have really shown an interest in the project, as such with your agreement I would add you to that new team.

Of course if you just wish to contribute with no maintenance responsibilities thats totally fine as well

**Comment by PF4Public** [comment]
Please note that even being part of a team does not mean you take some obligations, we obviously cannot request anything from anyone, but a pair (or two) of helping hands are always welcome.

**Comment by teeminus** [comment]
Me too!
