### ISSUE TITLE
file has a virus 

### ISSUE THREAD

**Issue by gsbnlda** [ungoogled-software/ungoogled-chromium-windows#146]
https://www.virustotal.com/gui/file/a4770e85e03c7f3563993ecc8a0289fcfd4f70bbc0119cfadc50a6627737aa51 , 

https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/102.0.5005.61

and from 3rd party website it has also a virus ,  https://www.techspot.com/downloads/7181-ungoogled-chromium.html , 

https://www.virustotal.com/gui/file/b10817dbdd91608fc00b537fb051e6b3c45aac010034e07c31e65f1558571e09

**Comment by PF4Public** [comment]
> and from 3rd party website it has also a virus , https://www.techspot.com/downloads/7181-ungoogled-chromium.html ,
> 
> https://www.virustotal.com/gui/file/b10817dbdd91608fc00b537fb051e6b3c45aac010034e07c31e65f1558571e09

We do not provide support for third-party binaries and I would not recommend downloading and installing them.

As for the https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/102.0.5005.61 we may inquire @Nifury about that.

**Comment by Nifury** [comment]
Well there have been multiple discussions on this. It's a false positive and personally I don't consider 2/64 detections alarming. Not all AV engines are of high quality, and some have a relatively high positive rate on unseen files. 
That being said, I'd recommend that you compile the project from the source code if that detection bothers you. 

https://github.com/CookieJarApps/SmartCookieWeb-Preview/discussions/98
https://github.com/ungoogled-software/ungoogled-chromium/discussions/1823
https://github.com/ungoogled-software/ungoogled-chromium/discussions/1787

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
