### ISSUE TITLE
Py build.py issue [ExtractionError]

### ISSUE THREAD

**Issue by Sarkalso** [ungoogled-software/ungoogled-chromium-windows#148]
![image](https://user-images.githubusercontent.com/105189837/173245102-aadac304-63be-433f-be87-605d1fde1e3d.png)

I installing 102.0.5005.115-1.1 but i encounter ExtractionError like this.
7.zip already in the file.
![image](https://user-images.githubusercontent.com/105189837/173245147-d04030b9-8cfc-4b99-9227-ec6960bc34dd.png)

**Comment by networkException** [comment]
You need to run the command promt as administrator

**Comment by teeminus** [comment]
Or you allow creation of symbolic links for non admin users.

**Comment by Sarkalso** [comment]
> 

i did,didt work for me

**Comment by Sarkalso** [comment]
> Or you allow creation of symbolic links for non admin users.

how?

**Comment by Nifury** [comment]
> > 
> i did,didt work for me

You also need to remove `build\src` folder before re-running build.py.

**Comment by teeminus** [comment]
> > Or you allow creation of symbolic links for non admin users.
> 
> 
> 
> how?
> 
> 

This can be done using `gpedit.msc` (run as admin). Navigate to `Computer Configuration\Windows Settings\Local Policies\User Rights Assignment` and add your user name to `create symbolic links`.

**Comment by Sarkalso** [comment]
> > > Or you allow creation of symbolic links for non admin users.
> > 
> > 
> > how?
> 
> This can be done using `gpedit.msc` (run as admin). Navigate to `Computer Configuration\Windows Settings\Local Policies\User Rights Assignment` and add your user name to `create symbolic links`. Reboot afterwards.

ok,i try it later

**Comment by Sarkalso** [comment]
> > > 
> > 
> > 
> > i did,didt work for me
> 
> You also need to remove `build\src` folder before re-running build.py.

i try again
