### ISSUE TITLE
Is new_version_check.yml needed?

### ISSUE THREAD

**Issue by PF4Public** [ungoogled-software/ungoogled-chromium-windows#158]
Would it be beneficial to have an adapted (linux → win) copy of new_version_check.yml from main repo here?

Sometimes Windows stable updated do not correspond to Linux updates. At the moment Windows is ahead of Linux at 103.0.5060.66 for example.

**Comment by teeminus** [comment]
Yes, that would be great. The quest is if the version check should be implemented here or in the core repo. I don't know if the patches of the core repo can be applied to a more recent (windows) chromium version.

**Comment by networkException** [comment]
Yea we probably at least need to shuffle some line number around.

I'd say we add it to the core repo with an additional windows tag and just require a review checking if it builds and runs from the windows team

Apparently you can also assign teams in an issue template so that would be fitting

**Comment by teeminus** [comment]
Wouldn't the core repo profit from using a more recent version of chromium as well? Sure, it's likely that only windows problems are addressed in the windows release, but I think it would not make the Linux version worse. Besides having an other build number than the official chrome release.

**Comment by networkException** [comment]
I'm not sure if we want to do that as it could accidentally introduce regressions that nobody else has on linux

**Comment by PF4Public** [comment]
The Stable channel has been updated to 103.0.5060.114 for Windows. which will roll out over the coming days/weeks. 

:D

**Comment by teeminus** [comment]
There seems to be some important security fixes for actively targeted bugs in that release...

So, how do we move forward on this?

**Comment by PF4Public** [comment]
There is no tarball yet anyway.

**Comment by networkException** [comment]
> There is no tarball yet anyway.

I think all downstream maintainers basically gave up on that getting available

> So, how do we move forward on this?

I think we should have patchset releases (and as such a workflow and issues with seperate platform tags) for every version that targets at least one actively maintained platform

**Comment by PF4Public** [comment]
I think, we've handled it it main repo.
