### ISSUE TITLE
Will the compiler inject something?

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#161]
Story:
[Visual Studio 2015 C++ Compiler Secretly Inserts Telemetry Code Into Binaries](https://yro.slashdot.org/story/16/06/10/1350245/visual-studio-2015-c-compiler-secretly-inserts-telemetry-code-into-binaries)

A simple HelloWorld can be tested.

**Comment by playgithub** [comment]
But it might be a private version.

**Comment by sevmonster** [comment]
Your concern is covered [on the front page](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) that builds are community-maintained and not guaranteed to be reproducible. You are trusting the community, just as you would trust Google, that the software being provided is fit to function and not malicious. You are also trusting the chosen compiler toolchain, build host, storage cluster, network transport, your own operating system, and everything else. If you don't trust these things, your only real alternative is to audit the source for everything and compile it yourself...
