### ISSUE TITLE
Compile "Official Build"

### ISSUE THREAD

**Issue by Fei1Yang** [ungoogled-software/ungoogled-chromium-windows#163]
Flag `is_official_build=true` enables some optimizations and other Ungoogled Chromium distributions ([Debian](https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/9d2feeb585e0cb6a10d290773421417336ea3d94/debian/rules#L55), [Portable Linux](https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/blob/master/flags.portable.gn#L9)) also enable this.

It should also be enabled for the Windows distribution.

**Comment by teeminus** [comment]
Fixed with 103.0.5060.134-1.2
