### ISSUE TITLE
I can't open links

### ISSUE THREAD

**Issue by DAIIIIIIIIIIIIII** [ungoogled-software/ungoogled-chromium-windows#165]
let's say that from the telegram ap pc send me a link. if I click on the link they sent me (so all the links), it does not open me ungoogled chromium (no there are no other browsers on the pc); nothing just happens

**Comment by tomasz1986** [comment]
Is the browser registered as the default in the Windows settings (see https://howtogeek.com/767462/how-to-change-the-default-web-browser-on-windows-11)?

**Comment by DAIIIIIIIIIIIIII** [comment]
> Is the browser registered as default in the Windows settings (see [https://howtogeek.com/767462/how-to-change-the-default-web-browser-on-windows-11](http://www.smartredirect.de/redir/clickGate.php?u=IgKHHLBT&m=1&p=8vZ5ugFkSx&t=vHbSdnLT&st=&s=&url=https%3A%2F%2Fhowtogeek.com%2F767462%2Fhow-to-change-the-default-web-browser-on-windows-11&r=https%3A%2F%2Fgithub.com%2Fungoogled-software%2Fungoogled-chromium-windows%2Fissues%2F165))?

yes it it... but i have some misunderstanding with chrlauncher

**Comment by teeminus** [comment]
Isn't chrlauncher using a version/release of ungoogled-chromium-windows that is not related to this repo?

**Comment by PF4Public** [comment]
We do not provide support for third-party binaries and I would not recommend downloading and installing them.
If you're seeking support file this issue with the repository you've downloaded the binary from.
