### ISSUE TITLE
Installer icon for Ungoogled-Chromium has compression artifacting

### ISSUE THREAD

**Issue by TalhaErenY** [ungoogled-software/ungoogled-chromium-windows#172]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

105.0.5195.102 (Official Build, ungoogled-chromium) (64 bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile and it could not be reproduced there

### Description

The current installer icon is broken and has significant image compression.

### How to Reproduce?

1. Download the installer.exe
2. Look at the file on a directory with icons enabled.

### Actual behaviour

an update between 102 and 105 has broken the installer icon to a compressed version

### Expected behaviour

the icon should use default windows installer iconset

### Additional context

![compressedIcon](https://user-images.githubusercontent.com/85240220/188586674-ea67745a-177c-48bb-888f-4e216a3a3f15.png)

**Comment by teeminus** [comment]
The installer logo is part of the chromium sources, it's an 32x32 pixel ico file.

**Comment by TalhaErenY** [comment]
Has it always been this way and I just misremembered then? I've managed to download v97, it is the same. It seemed odd to see a non-standart installer icon.

**Comment by teeminus** [comment]
It's not a standard windows installer but a custom installer (basically a self extracting archive). All sources for the installer are part of the chromium project.

**Comment by TalhaErenY** [comment]
Apologies for the confusion, I'll close this now as it isn't a bug.
