### ISSUE TITLE
HELP me please How i ican repair ungoogled-chromium-portable.exe

### ISSUE THREAD

**Issue by tee4341** [ungoogled-software/ungoogled-chromium-windows#175]
HELP me please How In Detail tjprojmain.exe attack ungoogled-chromium-portable.exe
![screenshot 2022-09-18](https://user-images.githubusercontent.com/48321898/190880896-257dc0c7-17db-4b26-b660-bb0590052692.jpg)

**Comment by networkException** [comment]
What do you want us to do here? You downloaded a random executable from the internet which we have nothing to do with and thats probably a virus
