### ISSUE TITLE
Upgrade Unchromium portable Windows x64

### ISSUE THREAD

**Issue by tipitao** [ungoogled-software/ungoogled-chromium-windows#185]
Hi good morning. There is any metod to update in futures version?. If it's not posible, how i can to save my profile?. There is any tool to make backup of profiles ?

Thanks & regards

Pd. Sorry my poor english

**Comment by Rusenche** [comment]
Hello.

If you're using a portable version, you can back up the "User Data" folder - that's where the settings are. With a new version - you can carry over this "User Data" folder and continue with new versions in this way.

There is one tool that doesn't support this repository yet https://github.com/ungoogled-software/ungoogled-chromium-windows/. More than 3 months ago I wrote to the developer @henrypp to add support, but he categorically does not say... Here is the thread: https://github.com/henrypp/chrlauncher/issues/217

**Comment by tipitao** [comment]
Ok thanks
