### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Rusenche** [ungoogled-software/ungoogled-chromium-windows#186]
After posting my comment here: https://chromium.woolyss.com/#comment-8512

I quote:
```
Hello.

I have a problem with the following.

Until Ungoogled Chromium v.106.0.5249.119 x64 (by marmaduk) I didn't have this problem that I have with Ungoogled Chromium v.107.0.5304.88 x64.

With these settings:
1. chrome://settings/privacy -> Security -> Use secure DNS -> enable/check it.
2. With Custom -> https://dns.adguard.com/dns-query.

And every time on some sites I get: "ERR_TOO_MANY_REDIRECTS"

I am attaching two pictures to visualize the settings:
https://i.postimg.cc/hj0LxJSp/1.png
https://i.postimg.cc/gjkvKYjd/2.png

The problem is only fixed when you disable "Use secure DNS" and then the problem site loads.

For verification, I also tested https://github.com/Hibbiki/chromium-win64/releases/tag/v107.0.5304.88-r1047731 - on Hibbiki.

But it's the same there.

For reference: Each test is done with portable version and without any settings, tests are done with new profile and with new settings.

I'm not posting this to the marmaduk repository because it will lock the thread there and not respond.

The sites that cause me problems are for example: https://2baksa.ws/ and https://arenabg.com/torrents/.

Please, for example, Hibbiki to test.

Because I just tested with Hibbiki's https://github.com/Hibbiki/chromium-win64/releases/tag/v106.0.5249.91-r1036826 - no problem at all.

I also tested with the flag chrome://flags/#enable-webrtc-hide-local-ips-with-mdns - I don't know if it has any relevance, but whether it will be Enabled, Default or Disables - no change.

So... What is the cause of this problem?!
```

Addendum: I tested with the portable version - https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/download/107.0.5304.63-1.1/ungoogled-chromium_107.0.5304.63-1.1_windows_x64.zip

The problem is here too. Could it be due to how to put it properly and accurately....the developments of @Eloston, @Ahrotahn and this problem just hasn't been noticed?!

I'm posting about the issue here because if it's in the repository https://github.com/ungoogled-software/ungoogled-chromium/issues - they'll answer that it's a foreign development by @marmaduk and @Hibbiki. And so...

Can you take a look and track down my issue which only appears since version 107?! Or forward the thread to @Eloston, @Ahrotahn for further investigation and fix the "ERR_TOO_MANY_REDIRECTS" issue.

**Comment by PF4Public** [comment]
We do not provide support for binaries obtained outside of [ungoogled-software](https://github.com/ungoogled-software) GitHub organisation and I would not recommend downloading and executing them. Usage of `chrlauncher` is also discouraged.
If you're seeking support report this issue to where you've obtained the binary.

**Comment by Rusenche** [comment]
Thanks for the 10 months later some kind of response that does absolutely nothing and in no way to help resolve the issue. As seen from 10 months ago - tested exactly with the binaries from the project: https://github.com/ungoogled-software/ungoogled-chromium-windows/. I don't even understand what the connection is with `chrlauncher`... The topic is written in its exact and correct place, but as always - there is always no adequate answer.

...

Closing the topic.
