### ISSUE TITLE
annoying message for Win7/8/8.1 users since Chromium 108

### ISSUE THREAD

**Issue by stano22** [ungoogled-software/ungoogled-chromium-windows#193]
Hi team,
many thanks for your nice work regarding this project.
I use Win7 (also I will continue to use Win7) and since version 108, there is annoying message/warning with every run of ungoogled-chromium:
"To get future Chromium updates, you´ll need Windows 10 or later. This computer is using Windows 7."
There is a solution to create a new registry entry for Chromium policies (SuppressUnsupportedOSWarning), but after using this workaround, Chromium will state "Managed by your organization" and it means another issue - Secure DNS is not available (grayed out) in browser Settings and therefore browser starts to use system DNS instead.
I cannot find any flag or switch to remove this annoyance.
Is there any solution or planned patch to get rid of this annoying message for Win7/8/8.1 users?

**Comment by networkException** [comment]
I think we should consider this but its ultimately up to the windows maintainers

See also https://github.com/ungoogled-software/ungoogled-chromium/discussions/2173

**Comment by stano22** [comment]
It is no problem for me to stay on 109 (the last supported Chromium version for Win7), but this message/warning is really annoying with every run of browser.
Regarding #2173: to disable infobar completely is not a solution, because infobar also shows useful info (about extensions etc.).

**Comment by Rusenche** [comment]
@stano22

A working solution without any negative consequences or limitations: **–test-type=ui**

**Comment by Rusenche** [comment]
@stano22

A working solution without any negative consequences or limitations: **--test-type=ui**

**Comment by greenozon** [comment]
a question regarding Windows 7: was the support of w7 dropped due to start using some w10 only WinAPI?
or this is just a political decition by Google and one could build up binaries for w7 even from say version 112?

**Comment by Nicolai-Nielsen** [comment]
will this problem ever be fixed or does anyone have a better fix?
Thanks.

**Comment by PF4Public** [comment]
> will this problem ever be fixed or does anyone have a better fix?

It is not an issue of ungoogled-chromium, so please be mindful with your demands.

**Comment by Nicolai-Nielsen** [comment]
> > will this problem ever be fixed or does anyone have a better fix?
> 
> It is not an issue of ungoogled-chromium, so please be mindful with your demands.

https://wikiless.org/wiki/Question_mark?useskin=monobook&lang=en#Scope

**Comment by TorutheRedFox** [comment]
> > will this problem ever be fixed or does anyone have a better fix?
> 
> It is not an issue of ungoogled-chromium, so please be mindful with your demands.

it's an issue for the windows maintainers for as long as they plan on maintaining support for these versions (since it's false until support is dropped)

**Comment by tomasz1986** [comment]
Support has been gone for a long time. The last version that can run on Windows 7 and 8 is Chromium 109. We are at v117 right now.

**Comment by greenozon** [comment]
why not v118?
