### ISSUE TITLE
Update to version 77

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-windows#2]
Continuation of https://github.com/Eloston/ungoogled-chromium/issues/619 and https://github.com/Eloston/ungoogled-chromium/issues/675.

I have updated `build.py` and `package.py` for the new system (post-fragmentation refactor). The rest of the work should be updating GN flags and patches.

**Comment by hardhub** [comment]
Reposting from old issue:

I tried latest master version (new build instructions) and result is still error:

```
INFO: Applying patches from patches
Traceback (most recent call last):
  File "C:\ungoogled-chromium\utils\patches.py", line 162, in <module>
    main()
  File "C:\ungoogled-chromium\utils\patches.py", line 158, in main
    args.callback(args)
  File "C:\ungoogled-chromium\utils\patches.py", line 116, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "C:\ungoogled-chromium\utils\patches.py", line 35, in apply_patches
    raise ValueError('Could not find the patch binary')
```

It expects patch.exe available on disk but it is missing.

--

Also I tried to use `py build.py` command for windos repo but it also does not work:

```
C:\ungoogled-chromium-windows>py build.py
INFO: Downloading required files...
Traceback (most recent call last):
  File "build.py", line 209, in <module>
    main()
  File "build.py", line 141, in main
    downloads.retrieve_downloads(download_info, args.downloads_cache, True,
AttributeError: 'Namespace' object has no attribute 'downloads_cache'
```

**Comment by tonkku107** [comment]
I fixed the problem in build.py by adding `args.downloads_cache = _ROOT_DIR / 'build' / 'downloads_cache'` below line 122

after that many of the patches fail to apply and one can't find the file it's looking for.

**Comment by Eloston** [comment]
@tonkku107 The patches will need to be updated for 73, which is why you're seeing that error with patches.

**Comment by r4sas** [comment]
btw, adding list of files without substitutions:

```
INFO: Path has no substitutions: chrome/browser/plugins/plugins_resource_service.cc
INFO: Path has no substitutions: chrome/browser/safe_browsing/client_side_model_loader.cc
INFO: Path has no substitutions: chrome/common/google_url_loader_throttle.cc
INFO: Path has no substitutions: chrome/common/page_load_metrics/page_load_metrics_util.cc
INFO: Path has no substitutions: components/dom_distiller/content/browser/dom_distiller_viewer_source.cc
INFO: Path has no substitutions: components/dom_distiller/core/html/preview.html
INFO: Path has no substitutions: components/domain_reliability/google_configs.cc
INFO: Path has no substitutions: components/google/core/browser/google_url_tracker.cc
INFO: Path has no substitutions: components/variations/net/variations_http_headers.cc
INFO: Path has no substitutions: net/tools/transport_security_state_generator/transport_security_state_generator.cc
INFO: Path has no substitutions: rlz/lib/lib_values.cc
INFO: Path has no substitutions: third_party/catapult/third_party/polymer/components/font-roboto/roboto.html
INFO: Path has no substitutions: third_party/catapult/tracing/third_party/gl-matrix/jsdoc-template/static/default.css
INFO: Path has no substitutions: third_party/crashpad/crashpad/doc/support/crashpad_doxygen.css
INFO: Path has no substitutions: tools/md_browser/base.css```

**Comment by Eloston** [comment]
@r4sas That's fine. Those files are probably patched or removed, so they show up as files without substitution. Domain substitution is computed based on the original Chromium source tree (i.e. without any modifications).

**Comment by tonkku107** [comment]
The gn bootstrap script expects to find ninja from the path. Maybe the build script should be updated to add the path of the downloaded ninja to path?

Then there's this error at the gn gen phase
```
ERROR at //chrome/browser/BUILD.gn:4090:5: Label not in deps.
    allow_circular_includes_from += [
    ^--------------------------------
The label "//chrome/browser/safe_browsing:safe_browsing"
was not in the deps of this target. allow_circular_includes_from only allows
targets present in the deps.
See //build/config/jumbo.gni:257:3: whence it was called.
  internal_jumbo_target(target_name) {
  ^-----------------------------------
See //chrome/browser/BUILD.gn:75:1: whence it was called.
jumbo_split_static_library("browser") {
^--------------------------------------
See //chrome/BUILD.gn:168:11: which caused the file to be included.
          "//chrome/browser:active_use_util",
          ^---------------------------------
```

**Comment by r4sas** [comment]
> The gn bootstrap script expects to find ninja from the path. Maybe the build script should be updated to add the path of the downloaded ninja to path?

Here problem not in ninja,
Remove line 1714 in `chrome\browser\BUILD.gn`:
`    "//chrome/browser/safe_browsing",`

**Comment by tonkku107** [comment]
That error was after adding the location of ninja.exe to path, if that was unclear.

**Comment by r4sas** [comment]
Ah, I think that you said about ninja according to error =)

**Comment by tonkku107** [comment]
So, how is this going to progress? Chrome 74 was released to stable yesterday.

**Comment by Eloston** [comment]
Yes, and ungoogled-chromium's been updated to 74 as well. Do you guys want to switch to 74?

**Comment by tonkku107** [comment]
I would switch to 74, yes.

**Comment by PonyPC** [comment]
> The gn bootstrap script expects to find ninja from the path. Maybe the build script should be updated to add the path of the downloaded ninja to path?
> 
> Here problem not in ninja,
> Remove line 1714 in chrome\browser\BUILD.gn:
>     "//chrome/browser/safe_browsing",
> There is many changes needed to remove safe_browsing....

also need remove "//chrome/browser/safe_browsing" in "chrome\browser\extensions\BUILD.gn",  "chrome\browser\ui\BUILD.gn",
move '''source_set("binary_feature_extractor") {
    sources = [
      "pe_image_reader_win.cc",
      "pe_image_reader_win.h",
    ]
  }''' out side '''if (safe_browsing_mode == 1) {''' in "chrome\common\safe_browsing\BUILD.gn"

Then next step I meet:
'''FAILED: obj/chrome/elevation_service/elevation_service/elevation_service.res
E:/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../build/toolchain/win/tool_wrapper.py rc-wrapper environment.x64 rc.exe /nologo -DUSE_AURA=1 -DNO_TCMALLOC -DOFFICIAL_BUILD -DCHROMIUM_BUILD "-DCR_CLANG_REVISION=\"354873-1\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNTDDI_VERSION=NTDDI_WIN7 -D_WIN32_WINNT=_WIN32_WINNT_WIN7 -DWINVER=_WIN32_WINNT_WIN7 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -I../.. -Igen -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src /foobj/chrome/elevation_service/elevation_service/elevation_service.res ../../chrome/elevation_service/elevation_service.rc

../../chrome/elevation_service/elevation_service.rc(38) : error RC2135 : file not found: chrome/elevation_service/elevation_service_idl.tlb'''

**Comment by PonyPC** [comment]
Then I success build, but chrome.exe cannot run correctly. need fix later.

**Comment by tonkku107** [comment]
Create a PR with updated patches for your changes?

**Comment by PonyPC** [comment]
I'm sorry I can't confirm my patch is correct... @tonkku107

**Comment by tonkku107** [comment]
@Eloston or someone else will review the patches. If something's wrong you'll get feedback and you can update the patches again.

**Comment by PonyPC** [comment]
The patch still need to be fix for running. I'll try later.

**Comment by evo744** [comment]
So it's 21 days later, with the modifications it builds and just crashes at startup. The last build for windows is version 67. Anyone still working on this?

**Comment by PonyPC** [comment]
@evo744 I'm still finding the crash issue. But it seems that it beyonds my ability. 😂😂😂
Maybe you can help this project.

**Comment by evo744** [comment]
@PonyPC I'm trying, maybe I'll get lucky

**Comment by tangalbert919** [comment]
I managed to fix the patches so they apply correctly this time. However, expect this error:

```
ERROR at //tools/grit/grit_rule.gni:101:3: Assertion failed.
  assert(
  ^-----
resource whitelist generation only works on non-component builds with debug info enabled.
See //tools/grit/grit_rule.gni:102:7:
      symbol_level > 0 && !strip_debug_info && !is_component_build,
      ^-----------------------------------------------------------
This is where it was set.
See //net/BUILD.gn:16:1: whence it was imported.
import("//tools/grit/grit_rule.gni")
^----------------------------------
See //BUILD.gn:69:5: which caused the file to be included.
    "//net:net_unittests",
    ^--------------------
```

**Comment by maxk1968** [comment]
> 
> 
> I managed to fix the patches so they apply correctly this time. However, expect this error:
> 
> ```
> ERROR at //tools/grit/grit_rule.gni:101:3: Assertion failed.
>   assert(
>   ^-----
> resource whitelist generation only works on non-component builds with debug info enabled.
> See //tools/grit/grit_rule.gni:102:7:
>       symbol_level > 0 && !strip_debug_info && !is_component_build,
>      ...
> See //BUILD.gn:69:5: which caused the file to be included.
>     "//net:net_unittests",
>     ^--------------------
> ```

_I have a similar problem:_

ERROR at //tools/grit/grit_rule.gni:101:3: Assertion failed.
  assert(
  ^-----
resource whitelist generation only works on non-component builds with debug info enabled.
See //tools/grit/grit_rule.gni:102:7:
      symbol_level > 0 && !strip_debug_info && !is_component_build,
      ^-----------------------------------------------------------
This is where it was set.
See //tools/grit/repack.gni:5:1: whence it was imported.
import("//tools/grit/grit_rule.gni")
^----------------------------------
See //components/BUILD.gn:15:1: whence it was imported.
import("//tools/grit/repack.gni")
^-------------------------------
See //BUILD.gn:87:7: which caused the file to be included.
      "//components:components_unittests",
      ^----------------------------------

**Comment by tangalbert919** [comment]
It looks like for this, we need to disable `enable_resource_whitelist_generation` to fix that error. Adding the following entry to `flags.windows.gn` will do just that:

`enable_resource_whitelist_generation=false`

**Comment by maxk1968** [comment]
Added flag `enable_resource_whitelist_generation=false` and got an error similar to https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2#issuecomment-485256254 ahhh! I really want to try to use ungoogle-chromium-windows. Maybe there are suggestions on how to move the process forward.

```
ERROR at //chrome/browser/ui/BUILD.gn:3419:5: Label not in deps.
    allow_circular_includes_from += [
    ^--------------------------------
The label "//chrome/browser/safe_browsing:safe_browsing"
was not in the deps of this target. allow_circular_includes_from only allows
targets present in the deps.
See //build/config/jumbo.gni:279:3: whence it was called.
  internal_jumbo_target(target_name) {
  ^-----------------------------------
See //chrome/browser/ui/BUILD.gn:29:1: whence it was called.
jumbo_split_static_library("ui") {
^---------------------------------
See //chrome/browser/devtools/BUILD.gn:233:7: which caused the file to be included.
      "//chrome/browser/ui",
      ^--------------------
```

**Comment by Kieaer** [comment]
```
[175/175] LINK gn.exe
FAILED: gn.exe
ninja -t msvc -- link.exe /nologo /OUT:gn.exe /PDB:gn.exe.pdb @gn.exe.rsp
LINK : fatal error LNK1181: 'dbghelp.lib' can not open input file.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "tools\gn\bootstrap\bootstrap.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools\gn\bootstrap\bootstrap.py", line 128, in main
    ['ninja', '-C', gn_build_dir, 'gn.exe', '-w', 'dupbuild=err'])
  File "C:\Users\cloud\depot_tools\win_tools-2_7_15_chromium14_bin\python\bin\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'C:\\Users\\cloud\\work\\ungoogled-chromium-windows\\build\\src\\out\\Release\\gn_build', 'gn.exe', '-w', 'dupbuild=err']' returned non-zero exit status 1
C:\Users\cloud\work\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "build.py", line 210, in <module>
    main()
  File "build.py", line 199, in main
    '--skip-generate-buildfiles')
  File "build.py", line 67, in _run_build_process
    **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

C:\Users\cloud\work\ungoogled-chromium-windows>
```

How to solve this?

**Comment by Kieaer** [comment]
OK, I solve dbghelp.lib not found __bug__.
However, there was an error presumed to be the source's own problem.
```
[175/175] LINK gn.exe
FAILED: gn.exe
ninja -t msvc -- link.exe /nologo /OUT:gn.exe /PDB:gn.exe.pdb @gn.exe.rsp
base.lib(command_line.obj) : error LNK2001: __imp_CommandLineToArgvW 외부 기호를 확인할 수 없습니다.
gn_lib.lib(command_args.obj) : error LNK2001: __imp_ShellExecuteExW 외부 기호를 확인할 수 없습니다.
gn.exe : fatal error LNK1120: 2개의 확인할 수 없는 외부 참조입니다.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "tools\gn\bootstrap\bootstrap.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools\gn\bootstrap\bootstrap.py", line 128, in main
    ['ninja', '-C', gn_build_dir, 'gn.exe', '-w', 'dupbuild=err'])
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'C:\\Users\\cloud\\work\\ungoogled-chromium-windows\\build\\src\\out\\Release\\gn_build', 'gn.exe', '-w', 'dupbuild=err']' returned non-zero exit status 1

C:\Users\cloud\work\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "build.py", line 210, in <module>
    main()
  File "build.py", line 199, in main
    '--skip-generate-buildfiles')
  File "build.py", line 67, in _run_build_process
    **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

C:\Users\cloud\work\ungoogled-chromium-windows>
```
@Eloston After this error, I tried various means, including resetting the PATH and running it directly in Visual Studio, but they all arrived at this error, and I was convinced that this was a 100% source problem.
I want the above error to be the key to the solution.

**Comment by diingus** [comment]
> Added flag `enable_resource_whitelist_generation=false` and got an error similar to [#2 (comment)](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2#issuecomment-485256254) ahhh! I really want to try to use ungoogle-chromium-windows. Maybe there are suggestions on how to move the process forward.
> 
> ```
> ERROR at //chrome/browser/ui/BUILD.gn:3419:5: Label not in deps.
>     allow_circular_includes_from += [
>     ^--------------------------------
> The label "//chrome/browser/safe_browsing:safe_browsing"
> was not in the deps of this target. allow_circular_includes_from only allows
> targets present in the deps.
> See //build/config/jumbo.gni:279:3: whence it was called.
>   internal_jumbo_target(target_name) {
>   ^-----------------------------------
> See //chrome/browser/ui/BUILD.gn:29:1: whence it was called.
> jumbo_split_static_library("ui") {
> ^---------------------------------
> See //chrome/browser/devtools/BUILD.gn:233:7: which caused the file to be included.
>       "//chrome/browser/ui",
>       ^--------------------
> ```

**Comment by diingus** [comment]
> Added flag `enable_resource_whitelist_generation=false` and got an error similar to [#2 (comment)](https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2#issuecomment-485256254) ahhh! I really want to try to use ungoogle-chromium-windows. Maybe there are suggestions on how to move the process forward.
> 
> ```
> ERROR at //chrome/browser/ui/BUILD.gn:3419:5: Label not in deps.
>     allow_circular_includes_from += [
>     ^--------------------------------
> The label "//chrome/browser/safe_browsing:safe_browsing"
> was not in the deps of this target. allow_circular_includes_from only allows
> targets present in the deps.
> See //build/config/jumbo.gni:279:3: whence it was called.
>   internal_jumbo_target(target_name) {
>   ^-----------------------------------
> See //chrome/browser/ui/BUILD.gn:29:1: whence it was called.
> jumbo_split_static_library("ui") {
> ^---------------------------------
> See //chrome/browser/devtools/BUILD.gn:233:7: which caused the file to be included.
>       "//chrome/browser/ui",
>       ^--------------------
> ```

I've had the same errors pop up, and the fix is to just remove the `safe_browsing` circular deps it fails on.

Currently I'm facing this error:
```
>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
ERROR Unresolved dependencies.
//chrome/browser/conflicts:module_info(//build/toolchain/win:win_clang_x64)
  needs //chrome/common/safe_browsing:binary_feature_extractor(//build/toolchain/win:win_clang_x64)
```

It seems trivial, if you know the `gn` build system. As far as I can tell, `safe_browsing` cannot be `import`ed, nor can the source/header pair it requires.

A naive approach would be copying the two over to `//chrome/browser/conflicts(:module_info)` and patching the namespace changes.

**Comment by diingus** [comment]
I managed getting through the meta-build system by copying the dependency source/header files to `chrome\browser\conflicts` as `module_info_binary_feature_extractor.cc` and `.h`.

I also changed the header guard to `CHROME_COMMON_SAFE_BROWSING_BINARY_FEATURE_EXTRACTOR_H_A` and the `.cc` include to `#include "chrome/browser/conflicts/module_info_binary_feature_extractor.h"`,

as well as adding
```
"module_info_binary_feature_extractor.cc",
"module_info_binary_feature_extractor.h",
```
in `chrome\browser\conflicts\BUILD.gn`'s `sources`

This got through to `ninja` target building (?) 
This leads to:
```
In file included from ../../chrome/browser/conflicts/module_info_binary_feature_extractor.cc:5:
In file included from ../..\chrome/browser/conflicts/module_info_binary_feature_extractor.h:19:
In file included from ../..\third_party/protobuf/src/google/protobuf/repeated_field.h:60:
In file included from ../..\third_party/protobuf/src/google/protobuf/stubs/casts.h:36:
../..\third_party/protobuf/src/google/protobuf/stubs/common.h(46,10):  fatal error: 'google/protobuf/stubs/port.h' file not found
#include <google/protobuf/stubs/port.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The `<>` includes cannot seem to resolve `third_party/protobuf/src/google...` header includes, and replacing `<google/etc/.../header.h>` with `"third_party/protobuf/src/google/etc/.../header.h"` seems to suppress the errors. 

The issue is that this needs to be regex automated since the entire `protobuf` folder has this issue, it would seem.

**Comment by TCB13** [comment]
@diingus thank you for your continuous effort!

**Comment by diingus** [comment]
After having replaced the foul `#includes`, this shows up:
```
../../chrome/browser/conflicts/module_info_binary_feature_extractor.cc(13,10):  fatal error: 'components/safe_browsing/proto/csd.pb.h' file not found
#include "components/safe_browsing/proto/csd.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
There exists a `csd.proto` file in that folder, it's just that it hasn't been generated. Any help with the issue of proto generation would be appreciated, as I've never touched the subsystem.

**Comment by diingus** [comment]
> After having replaced the foul `#includes`, this shows up:
> 
> ```
> ../../chrome/browser/conflicts/module_info_binary_feature_extractor.cc(13,10):  fatal error: 'components/safe_browsing/proto/csd.pb.h' file not found
> #include "components/safe_browsing/proto/csd.pb.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> There exists a `csd.proto` file in that folder, it's just that it hasn't been generated. Any help with the issue of proto generation would be appreciated, as I've never touched the subsystem.

Adding
```
public_deps = [
  "//components/safe_browsing:csd_proto",
]
```
to `chrome\browser\conflicts\BUILD.gn` seems to have fixed the issue. Currently compiling.

**Comment by diingus** [comment]
> Adding
> 
> ```
> public_deps = [
>   "//components/safe_browsing:csd_proto",
> ]
> ```
> 
> to `chrome\browser\conflicts\BUILD.gn` seems to have fixed the issue. Currently compiling.

An error cropped up saying `chrome\elevation_service\elevation_service_idl.idl` hadn't been compiled into a `.tlb`, which I had to do manually with `MIDL`.
It seems to be a remnant from `COM` programming and one of Microsoft's many bodges with the Visual C toolkit(s). As such, very little can be found on MSDN about it. `MIDL` is installed alongisde the Windows SDK, and running `vcvars64.bat` will get everything you need on your `PATH` to do `midl elevation_service_idl.idl`.

After reaching the 9300 job mark, the following happened:

```
In file included from gen/content/browser/browser_jumbo_15.cc:53:
.\../../content/browser/tracing/tracing_controller_impl.cc(188,8):  error: use of undeclared identifier 'coordinator_'
  if (!coordinator_) {
       ^
.\../../content/browser/tracing/tracing_controller_impl.cc(190,40):  error: use of undeclared identifier 'coordinator_'
        tracing::mojom::kServiceName, &coordinator_);
                                       ^
.\../../content/browser/tracing/tracing_controller_impl.cc(195,3):  error: use of undeclared identifier 'coordinator_'
  coordinator_ = nullptr;
  ^
.\../../content/browser/tracing/tracing_controller_impl.cc(367,3):  error: use of undeclared identifier 'coordinator_'
  coordinator_->StartTracing(
  ^
.\../../content/browser/tracing/tracing_controller_impl.cc(405,5):  error: use of undeclared identifier 'coordinator_'
    coordinator_->StopAndFlush(
    ^
.\../../content/browser/tracing/tracing_controller_impl.cc(411,5):  error: use of undeclared identifier 'coordinator_'
    coordinator_->StopAndFlushAgent(
    ^
.\../../content/browser/tracing/tracing_controller_impl.cc(425,3):  error: use of undeclared identifier 'coordinator_'
  coordinator_->RequestBufferUsage(base::BindOnce(
  ^
```

Reading the code, `coordinator_` appears only in class methods, suggesting it might be referencing `this->coordinator_`, but this causes
```
error: no member named 'coordinator_' in 'content::TracingControllerImpl'
```

**Comment by diingus** [comment]
`safe_browsing` seems to never be compiled, causing this:
```
LINK(DLL) chrome.dll chrome.dll.lib chrome.dll.pdb
FAILED: chrome.dll chrome.dll.lib chrome.dll.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:./chrome.dll.lib /DLL /OUT:./chrome.dll /PDB:./chrome.dll.pdb @./chrome.dll.rsp
lld-link.exe: error: could not open obj/chrome/browser/safe_browsing/safe_browsing.lib: no such file or directory
```

**Comment by tonkku107** [comment]
Remember that removal of safe browsing is part of ungoogled-chromium

**Comment by diingus** [comment]
The issues I'm facing so far are that of removing safe browsing integration, it seems. If I were to guess, more was delegated to that module, which hasn't been properly dealt with yet.
I'd take a shot at removing references, but I don't feel confident enough or knowledgeable enough to deal with those kinds of edits, especially when it comes to privacy issues.

As it stands, this thread was enough to get me to here.

**Comment by diingus** [comment]
For those interested, I've gathered the undefined reference errors caused by placing a dummy `safe_browsing.lib`:

- [log.txt](https://github.com/ungoogled-software/ungoogled-chromium-windows/files/3453507/log.txt)
- [mirror](https://pastebin.com/ju9e5ahb)

**Comment by Eloston** [comment]
I did some work on this in d2674a9204ba474b859fd2ddbcd820ad1455ea38. However, the Safe Browsing patch (and the few that follow) still need to be updated. #8 discusses what needs to be done with the Safe Browsing patch.

**Comment by Eloston** [comment]
Also, make sure to re-read the README. The build requirements have changed, and I've added my workflow for updating patches. Most notably, I dropped Python 2 because Google's working on porting all the Python scripts to Python 3, and it seems the ones we're using might be usable in Python 3. If not, we can cherry-pick changes from upstream.

**Comment by tangalbert919** [comment]
And so, the chaos in getting the latest version of Ungoogled Chromium built for Windows continues.

I've managed to get the build started, but expect an error like this:
```
ERROR at //third_party/protobuf/proto_library.gni:175:48: Array subscript out of range.
    proto_in_dir = get_path_info(proto_sources[0], "dir")
                                               ^
You gave me 0 but the array has no elements.
See //chrome/test/BUILD.gn:4976:3: whence it was called.
  proto_library("test_proto") {
  ^----------------------------
See //BUILD.gn:104:7: which caused the file to be included.
      "//chrome/test:browser_tests",
      ^----------------------------
```
This is triggered when `gn gen` is run.

**Comment by tangalbert919** [comment]
For those who want the latest version of Ungoogled Chromium for Windows (and not version 67), just click [here](https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/77.0.3865.90-1/ungoogled-chromium_77.0.3865.90-1.1_windows.zip).

With this, the chaos should be over. At least for a while.

**Comment by Eloston** [comment]
Thanks @tangalbert919! Since this issue is getting pretty long, please open a new issue if there are issues with the update.

**Comment by r4sas** [comment]
Yeah, thanks, @tangalbert919 :tada: 

But I want to ask: have anyone reproduced build and how result works for you?
I built with latest changes, but at the end I got that all pages is empty. Settings nor websites is not shown. Context menu (right mouse button) doesn't works too.
![image](https://user-images.githubusercontent.com/7023612/66271549-fe770800-e867-11e9-879d-fbfcd5e79fcf.png)

**Comment by Eloston** [comment]
@r4sas https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2#issuecomment-538730326. But yes, this is a pretty serious issue.

**Comment by hardhub** [comment]
> 
> 
> For those who want the latest version of Ungoogled Chromium for Windows (and not version 67), just click [here](https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/77.0.3865.90-1/ungoogled-chromium_77.0.3865.90-1.1_windows.zip).
> 
> With this, the chaos should be over. At least for a while.

Unfortunately it crashes on some pages.
