### ISSUE TITLE
How can I check the output of the program after I edit the code without having to build the whole project?

### ISSUE THREAD

**Issue by joja16** [ungoogled-software/ungoogled-chromium-windows#207]
How can I test the program after the change without having to build the whole project? Because the build takes a lot of time when I only fix a few places on the code.
You know, in any project, you need to fix the code many times before getting the right output, but the build time here is very long.
Does anyone have a method?

**Comment by ansoni-san** [comment]
Doing a component build may help you: https://chromium.googlesource.com/chromium/src/+/main/docs/component_build.md

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
