### ISSUE TITLE
The browser automatically sets the volume to the 100%.

### ISSUE THREAD

**Issue by Decation2** [ungoogled-software/ungoogled-chromium-windows#209]
When I watch videos on YouTube through this browser, it automatically sets the maximum volume and I listen through the speakers, and when the volume is turned on, my ears cannot stand it and I have to put it on the right volume myself so that it is not so loud. Please make your browser remember how much I set the volume, or there is such a setting as to automatically set a certain percentage of sounds.

**Comment by PF4Public** [comment]
I would guess that it is not the browser that is setting 100% volume, but it is Youtube that is "forgetting" the volume level you had set recently. Did you change "clear cookies upon exit" setting?

**Comment by Decation2** [comment]
PF4Public, I set it to allow all cookies, but YouTube doesn't remember what number I set. And I added youtube.com to allow using cookie files and others cookie files.

**Comment by Decation2** [comment]
Oh, thanks for advice!
