### ISSUE TITLE
I'm trying to develop ungoogleed chromium using visual studio code on windows, but all the tutorials seem to be available on debian only.

### ISSUE THREAD

**Issue by joja16** [ungoogled-software/ungoogled-chromium-windows#210]
I have searched everywhere but not clear for ungoogled chromium development on windows. 

After fixing some code with visual studio code, I tried to build again with py build.py but I couldn't.

Did I do something wrong? Look forward to the help.

**Comment by Nifury** [comment]
Normally you need to remove the `build/src` folder for build.py to work. 

In your case, you can try `py build.py --ci`. It should only recompile the modified files.

**Comment by joja16** [comment]
@Nifury Thank you so much for this helpful guide. But where will I develop code using VS?
I only see the code after successfully downloaded will be compressed at build\download_cache. It's different from developing on chromium source code.

**Comment by Nifury** [comment]
The source is located at `build/src`. It will be unpacked by the build script. 

Here is an instruction on how to generate VS solution file, but I don't guarantee it works for this project. 
https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#editing-and-debugging-with-the-visual-studio-ide

**Comment by joja16** [comment]
So what IDE are you developing with? I'm thinking everyone developing using VS on windows for this project.

**Comment by Nifury** [comment]
Visual Studio. I only make minor changes so I'm fine without intellisense. I just use VS for code indentation. 🤣

**Comment by joja16** [comment]
How wonderful. You have helped me troubleshoot for the past 1 week. But maybe I keep getting confused: on the side, you said I would delete the build/src folder for build.py. But did you just say you edited the code at build/src? 
So after you edit the code and you delete it again, build/src is spawned from build/download_cache again without any changes. You didn't make any modifications at build/download_cache did you?
Sorry for my silly questions.

**Comment by Nifury** [comment]
Running build.py without `--ci` will unpack the tarball, apply patches and everything. That's why you need to delete the build/src folder in that case. 

Adding `--ci` will skip those steps and triggers compilation directly, so you don't need to delete the folder if you have this argument.

**Comment by joja16** [comment]
Thanks so much, @Nifury
