### ISSUE TITLE
customize and debug changes

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#219]
I want to make a custom browser with ungoogled chromium, is there a way to preview my changes without having to create a package/release every time like chromium you can build using autoninja and then run a debug with out\Default\chrome

**Comment by PF4Public** [comment]
> then run a debug with out\Default\chrome

Yes

**Comment by infinitegame111** [comment]
Do you know what the command is?

**Comment by PF4Public** [comment]
Please provide more information on the issue, so that someone could help you further.

**Comment by infinitegame111** [comment]
I have changed the chromium icon so that way the application settings everything that uses the chromium icon is changed these are my local changes and I'm looking for the command to upload them that way when I do out\Default\chrome it will show the changes, with default chromium you use autoninja to compile local changes so it looks like this: autoninja -C out\Default chrome and then out\Default\chrome autoninja allows you to build your custom changes. Is there a script I can run to compile my local changes and if so what is the script?

**Comment by PF4Public** [comment]
Please note that this is an issue tracker for windows platform, it is not a chat, and as such it is not the best place to ask this kind of questions.

W.r.t. your question: you do your changes, you compile as usual, you run `chrome` binary from `out` folder, you do not need to publish a package for that.

**Comment by infinitegame111** [comment]
is it possible you know the script so I can run it and compile my changes? I'm just looking for the one script, like build.py replaces fetch it does the same thing it downloads the source or package.py packages chromium. I'm looking for the command that will recompile my local changes that way I can do out\Default\chrome to preview my changes
