### ISSUE TITLE
issues with build.py

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#222]
Trying to recompile my local changes with build.py there are errors when doing so.

INFO: Unpacking "chromium" to ./ ...
ERROR: Temporary unpacking directory already exists: C:\Users\ryana\ungoogled-chromium-windows\build\src\chromium-112.0.5615.50
Traceback (most recent call last):
  File "C:\Users\ryana\ungoogled-chromium-windows\build.py", line 240, in <module>
    main()
  File "C:\Users\ryana\ungoogled-chromium-windows\build.py", line 172, in main
    downloads.unpack_downloads(download_info, downloads_cache, source_tree, extractors)
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 343, in unpack_downloads
    extractor_func(
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 225, in extract_tar_file
    _extract_tar_with_7z(sevenzip_bin, archive_path, output_dir, relative_to)
  File "C:\Users\ryana\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 103, in _extract_tar_with_7z
    raise ExtractionError()
_extraction.ExtractionError

C:\Users\ryana\ungoogled-chromium-windows>

**Comment by PF4Public** [comment]
Which steps have you performed to identify the issue yourself?

**Comment by infinitegame111** [comment]
trying to look for sub commands like autoninja clearing build_cache and trying to clean out gn gen out\Default

**Comment by infinitegame111** [comment]
when running autoninja:

C:\Users\ryana\ungoogled-chromium-windows\build\src>autoninja -C out\Default chrome
"C:\Users\ryana\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python3\bin\python3.exe" C:\Users\ryana\depot_tools\ninja.py -C out\Default chrome -j 10
ninja: Entering directory `out\Default'
[0/1] Regenerating ninja files
Traceback (most recent call last):
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\build\vs_toolchain.py", line 578, in <module>
    sys.exit(main())
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\build\vs_toolchain.py", line 574, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\build\vs_toolchain.py", line 398, in CopyDlls
    _CopyDebugger(target_dir, target_cpu)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\build\vs_toolchain.py", line 431, in _CopyDebugger
    raise Exception('%s not found in "%s"\r\nYou must install '
Exception: dbghelp.dll not found in "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\Debuggers\x64\dbghelp.dll"
You must install Windows 10 SDK version 10.0.22621.0 including the "Debugging Tools for Windows" feature.
ERROR at //build/toolchain/win/BUILD.gn:24:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
Current dir: C:/Users/ryana/ungoogled-chromium-windows/build/src/out/Default/
Command: C:/Python39/python3.exe C:/Users/ryana/ungoogled-chromium-windows/build/src/build/vs_toolchain.py copy_dlls C:/Users/ryana/ungoogled-chromium-windows/build/src/out/Default Release x64
Returned 1.
See //BUILD.gn:83:1: which caused the file to be included.
group("gn_all") {
^----------------
FAILED: build.ninja.stamp
./gn.exe --root=../.. -q --fail-on-unused-args --regeneration gen .
ninja: error: rebuilding 'build.ninja': subcommand failed

C:\Users\ryana\ungoogled-chromium-windows\build\src>

**Comment by infinitegame111** [comment]
the issue is perdured when running py build.py to recompile the source

**Comment by Nifury** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/6d2a1c4e79338c5f1bbc9b0cad22d306c47b753c/build.py#L234-L235

**Comment by teeminus** [comment]
Have you installed the correct version of the Windows SDK? You log output contains the line `You must install Windows 10 SDK version 10.0.22621.0 including the "Debugging Tools for Windows" feature.`

**Comment by infinitegame111** [comment]
Ok, I will install it as well though I'm trying to compile my changes do I don't know if this is the correct script.

**Comment by infinitegame111** [comment]
_run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome', 'chromedriver', 'mini_installer') output:

C:\Users\ryana\ungoogled-chromium-windows\build\src>_run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome', 'chromedriver', 'mini_installer')
'_run_build_process' is not recognized as an internal or external command,
operable program or batch file.

**Comment by infinitegame111** [comment]
oh, I'll add that to build.py thanks

**Comment by infinitegame111** [comment]
I do have the sdk installed

**Comment by infinitegame111** [comment]
I have the correct sdk installed for windows 10, the errors occur

**Comment by infinitegame111** [comment]
I've tired to make a new script:

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2019 The ungoogled-chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""
ungoogled-chromium build script for Microsoft Windows
"""

import sys
import time

if sys.version_info.major < 3 or sys.version_info.minor < 6:
    raise RuntimeError('Python 3.6+ is required for this script. You have: {}.{}'.format(
        sys.version_info.major, sys.version_info.minor))

import argparse
import os
import re
import shutil
import subprocess
import ctypes
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / 'ungoogled-chromium' / 'utils'))
import patches
from _common import ENCODING, USE_REGISTRY, ExtractorEnum, get_logger
sys.path.pop(0)

_ROOT_DIR = Path(__file__).resolve().parent
_PATCH_BIN_RELPATH = Path('third_party/git/usr/bin/patch.exe')


def _get_vcvars_path(name='64'):
    """
    Returns the path to the corresponding vcvars*.bat path

    As of VS 2017, name can be one of: 32, 64, all, amd64_x86, x86_amd64
    """
    vswhere_exe = '%ProgramFiles(x86)%\\Microsoft Visual Studio\\Installer\\vswhere.exe'
    result = subprocess.run(
        '"{}" -prerelease -latest -property installationPath'.format(vswhere_exe),
        shell=True,
        check=True,
        stdout=subprocess.PIPE,
        universal_newlines=True)
    vcvars_path = Path(result.stdout.strip(), 'VC/Auxiliary/Build/vcvars{}.bat'.format(name))
    if not vcvars_path.exists():
        raise RuntimeError(
            'Could not find vcvars batch script in expected location: {}'.format(vcvars_path))
    return vcvars_path


def _run_build_process(*args, **kwargs):
    """
    Runs the subprocess with the correct environment variables for building
    """
    # Add call to set VC variables
    cmd_input = ['call "%s" >nul' % _get_vcvars_path()]
    cmd_input.append('set DEPOT_TOOLS_WIN_TOOLCHAIN=0')
    cmd_input.append(' '.join(map('"{}"'.format, args)))
    cmd_input.append('exit\n')
    subprocess.run(('cmd.exe', '/k'),
                   input='\n'.join(cmd_input),
                   check=True,
                   encoding=ENCODING,
                   **kwargs)



_run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default', 'chrome',
                           'chromedriver', 'mini_installer')

still not working and build.py won't work either and once again I checked the sdk is the correct one with debug enabled

**Comment by Nifury** [comment]
You need `os.chdir(source_tree)` to run your new script. 

You can also use `py build.py --ci` to recompile.

**Comment by infinitegame111** [comment]
ok, will do I'll try it, I was also able to get ninja.exe to work by pasting in build/src but this happened

ninja: Entering directory `out\Default'
[0/1] Regenerating ninja files
[930/1057] ACTION //chrome:resource_allowlist(//build/toolchain/win:win_clang_x64)
FAILED: gen/chrome/chrome_resource_allowlist.txt
C:/Python39/python3.exe ../../tools/resources/generate_resource_allowlist.py -o gen/chrome/chrome_resource_allowlist.txt chrome.dll.pdb
Traceback (most recent call last):
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 165, in <module>
    main()
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 161, in main
    WriteResourceAllowlist(args)
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 140, in WriteResourceAllowlist
    resource_ids.update(func(input))
  File "C:\Users\ryana\ungoogled-chromium-windows\build\src\tools\resources\generate_resource_allowlist.py", line 85, in GetResourceAllowlistPDB
    undname = subprocess.Popen(['undname', name],
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
ninja: build stopped: subcommand failed.

**Comment by infinitegame111** [comment]
It worked! py build.py --ci was the command I was looking for, the sub for autoninja. Thanks a lot for helping and for the command!
