### ISSUE TITLE
why is this happening when I never even moded this file?

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#230]
C:\Users\ryana\ungoogled-chromium-windows\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome" "chromedriver" "mini_installer"
ninja: Entering directory `out\Default'
[0/1] Regenerating ninja files
[1817/2097] CXX obj/chrome/browser/ui/ui/extensions_toolbar_container.obj
../../chrome/browser/ui/views/extensions/extensions_toolbar_container.cc(358,18): warning: declaration shadows a local variable [-Wshadow]
    views::View* anchor_view = BrowserView::GetBrowserViewForBrowser(browser_)
                 ^
../../chrome/browser/ui/views/extensions/extensions_toolbar_container.cc(349,22): note: previous declaration is here
  views::View* const anchor_view = GetViewForId(iter->extension_id);
                     ^
1 warning generated.
[1944/2097] LINK chromedriver.exe chromedriver.exe.pdb

**Comment by PF4Public** [comment]
Is this an issue with ungoogled-chromium?
