### ISSUE TITLE
Data and extensions are deleted after closing Ungoogled Chromium

### ISSUE THREAD

**Issue by Teyrukon** [ungoogled-software/ungoogled-chromium-windows#231]
Version 107.0.5304.88
OS: Windows 11 Education Insider Preview

After closing and reopening Ungoogled Chromium, all my data and extensions were deleted. This problem has occurred multiple times and I have not been able to solve it by installing a fresh copy.

![image](https://user-images.githubusercontent.com/43781812/233814336-0fdf6670-3142-4fbf-a480-75e95bb86d84.png)
![image](https://user-images.githubusercontent.com/43781812/233814609-520e6a49-9f01-4bd0-b542-c27b949f1563.png)

### List of Extensions:
<details>
<summary>Extensions</summary>
  <summary>Canvas Blocker v3.0.0</summary>
  <summary>Chromium Web Store v1.5.3.1</summary>
  <summary>ClearURLs v1.26.0</summary>
  <summary>Dark Reader v4.9.63</summary>
  <summary>DeepL Übersetzer: Lesen und Schreiben in Fremdsprachen v1.4.0</summary>
  <summary>Free Download Manager v3.0.57</summary>
  <summary>Grammatik- und Rechtschreibprüfung – LanguageTool v6.2.5</summary>
  <summary>Honey: Automatische Coupons & Prämien v15.12.3</summary>
  <summary>HTTPS Everywhere v2022.5.24</summary>
  <summary>KeePassXC-Browser v1.8.6.1</summary>
  <summary>nightTab v7.3.0</summary>
  <summary>Popup Blocker (strict) v0.6.6</summary>
  <summary>Privacy Badger v2023.1.31</summary>
  <summary>SimpleLogin:Receive & Send emails anonymously v2.9.1</summary>
  <summary>SponsorBlock für YouTube - Überspringe gesponserte Videosegmente v5.4.1</summary>
  <summary>Startpage Privatsphäre-Schutz v1.1.5</summary>
  <summary>Startpage — Datenschutz-Suchmaschine v1.1.2</summary>
  <summary>Stylus v1.5.29</summary>
  <summary>Tampermonkey BETA v4.19.6181</summary>
  <summary>uBlock Origin v1.49.0</summary>
  <summary>Unhook - Remove YouTube Recommended Videos v1.6.2</summary>
  <summary>User-Agent Switcher and Manager v0.5.0</summary>
</details>

**Comment by PF4Public** [comment]
How did you install ungoogled-chromium. Why do you use such an old version?

**Comment by Teyrukon** [comment]
I have Chromium installed with Chocolatey and I often forget to update. I will update to the latest version. Thanks for the advice.
