### ISSUE TITLE
Chromium issue

### ISSUE THREAD

**Issue by Rusenche** [ungoogled-software/ungoogled-chromium-windows#239]
Hello

I'm not sure exactly how to write the subject of the issue, so I'm generally asking it as a Chromium issue and I'll describe why.

1. Open https://glasove.com/novini/hristo-ivanov-ne-sam-pravil-opit-da-predpazya-borisov-ot-svalyane-na-imuniteta-samo-obsazhdahme-evropeyskata-praktika

There is a hole on the site - the place I circle in red.

Here is a picture: https://postimg.cc/Tyxkgzkk

2. I tested this exact address with:
- https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/tag/113.0.5672.127-1.1 - portable x64;
- also tested with macchrome/marmaduk.
- also tested with Thorium (https://github.com/Alex313031/Thorium-Win/).

I specify that all these tests were done with completely standard settings of each browser without any extension installed and without any setting changed. I even tested with the VPN on - apparently the thing that has it on the site doesn't show/visualize.

Why am I writing all this?

Because after that I decided to try librewolf-112.0-1 as well. And to my surprise - here is a photo: https://postimg.cc/JtgLwQ41

I mention it again - no settings have been changed, no extensions have been installed on this browser either.

My conclusion is that of the three tests with Chromium browsers - none of them, for some reason unknown to me, visualize the thing that is there on the site, but there is a white hole on the page.

After testing with librewolf-112.0-1 I saw that there is a clip. I didn't know there was a clip there before.

The problem and the question is - why with any Chromium-based browser this clip is not visualized (again I remind you that every single Chromium browser is only with standard settings, does not have a single extension installed and is tested only with the portable x64 versions), while librewolf- 112.0-1 is showing a clip?!

Why?!

I hope the experts @macchrome, @Ahrotahn, @networkException, @teeminus will get involved.

Please test it yourself and share the results.

**Comment by CirnoT** [comment]
This is due to mixed content
```
Mixed Content: The page at 'https://glasove.com/novini/hristo-ivanov-ne-sam-pravil-opit-da-predpazya-borisov-ot-svalyane-na-imuniteta-samo-obsazhdahme-evropeyskata-praktika' was loaded over HTTPS, but requested an insecure frame 'http://embed.btv.bg/lbin/global/embed.php?v=2113047213'. This request has been blocked; the content must be served over HTTPS.
```

Chromium refuses to render frames from insecure context when page was loaded over secure context. I am unsure why your build of LibreWolf had no issue rendering it, per default Firefox should block mixed content with warning too (https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content):
```
 Blocked loading mixed active content “http://embed.btv.bg/lbin/global/embed.php?v=2113047213”
 ```

I have confirmed that LibreWolf 113.0.1-1 does indeed render frame content from insecure context when page was loaded securely, which significantly degrades security provided by Firefox by default. You should ask them this question, as that seems counter-intuitive given their goal of privacy and security.
> This project is a custom and independent version of Firefox, with the primary goals of privacy, security and user freedom.

**Comment by Rusenche** [comment]
The site is news. You don't even need a hypothesis if...

The amazing thing is that a news site published this video, which no Chrome based browser previews the clip. It's about a clip.

When I created the theme - minutes later I also tested with:
- https://github.com/Hibbiki/chromium-win64/releases/latest;
- https://github.com/RobRich999/Chromium_Clang/releases/latest;
- CatsXP;
- Brave.

But there was no point in adding to my previous opinion, because I made it clear that it applies to all Chromium-based browsers.

Still, it's strange to me that a clip is a threat to Chromium's security...

I enter the hypothesis - someone sends me a link to this and/or another news site with a similar publication of a clip to read the article and watch the clip. And it turns out that a clip will never display/render with Chromium, which is crazy.

**Comment by ansoni-san** [comment]
Insecure content is insecure content. It poses a real risk to the security of your own information and online activity, not the browser process's security. 

Browsers caring about privacy should not allow a website which displays a promise of security (the padlock telling users their information is secure) to serve content which is not secure and can be seen in plaintext. 

The website in question should either serve the whole page as insecure so the users can consume insecure content while knowing it isn't secure, or make the content actually secure.
