### ISSUE TITLE
Chromimum not building in windows : midl.exe output different from files in gen/chrome/elevation_service

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-windows#24]
Replaces https://github.com/Eloston/ungoogled-chromium/issues/857#issue-519211155.

**Comment by tangalbert919** [comment]
I cannot reproduce this error unless I exclude `windows-disable-win-build-output.patch`. Is anyone else able to reproduce this error?

**Comment by Eloston** [comment]
Closing due to lack of info and inactivity.

**Comment by tinggo** [comment]
@Eloston how did you resolve the issue?
