### ISSUE TITLE
I just wanted to ask about the results I got from BrowserAudit

### ISSUE THREAD

**Issue by matsushita1918** [ungoogled-software/ungoogled-chromium-windows#241]
It seems that on browseraudit, ungoogled has one critical error, I am hoping the tests would be helpful in making this awesome and incredible fork of chrome even better and more secure. So I was wondering if there would be a way to fix this in a future update, I'm not an expert, or a coder, but would hope that this can be of any help, I am thankful to everyone here who works tirelessly on creating the best chrome based browser out there!  Here is said critical error with the description 
When a cookie has the Secure attribute set, a compliant browser will include the cookie in an HTTP request only if the request is transmitted over a secure channel, i.e. an HTTPS request. This keeps the cookie confidential; an attacker would not be able to read it even if he were able to intercept the connection between the victim and the destination server.

The Secure flag is supported by all major browsers.

We have four tests, testing the behavior of the Secure flag both when the cookies are set by the server and set by JavaScript. In each pair of tests, the first checks that a cookie with the Secure flag is sent to the server with an HTTPS request. The second test is the interesting one: it checks that a secure cookie is not sent with a request over plain HTTP.

Block | cookie set by JavaScript should not be sent over HTTP This critical test executed in ≈222ms and failed for the following reason: The cookie was sent to the server. function() {
  var thisTest = this;
  $.cookie("sessionSecureCookie", "910", {
    secure: true,
    path: "/",
    domain: ".browseraudit.com"
  });
  $("<img>", {
    src: "http://browseraudit.com/set_session_secure_cookie"
  }).load(function() {
    $.get("/get_session_secure_cookie", function(data) {
      if (data === "nil") {
        thisTest.PASS("The cookie was not sent to the server.");
      } else {
        thisTest.CRITICAL("The cookie was sent to the server.");
      }
    });
  });
} some of the text got garbled, but it is easily redouble to run this test your self on browser audit. There are 16 warnings and 20 skipped results after testing https://browseraudit.com/

**Comment by PF4Public** [comment]
Have you tried the same test in vanilla Chromium?

**Comment by matsushita1918** [comment]
> 

Not yet since I haven't had it installed for a very long time, this version of Chrome you guys have created is far more ram efficient, even when opening multiple tabs, the stock version that I remember and even the latest version of edge seems to have a problem with ram consumption over time, almost like a memory leak, It's tests on browseraudit that I can remember are pretty much the same as stock chrome. Far as Firefox is a bit like that too with the ram consumption creeping over time tho it does test better, it just isn't as compatible with everything like chrome is, I did however test Firefox, which according to that test is still technically more secure than chrome which it has 0 critical errors, 371 passed tests, only 13 warnings and the same 20 skipped tests, a closer look reveals that the 20 are flash related since flash has been gone for a long time, so the 20 skipped results don't matter really. I would include everything here via a link but it unfortunately includes my ip and it conducts such a detailed test that it would take forever to document all of them. The test itself only takes 5 mins or so to complete, so it would be cool if you guys could try this for your self on ungoogled, maybe that data can be useful, Ill say that on FF does take a bit longer likely due to the site being more favorable to chrome.

**Comment by PF4Public** [comment]
It would be great if you could try vanilla Chromium. I tend to think that this might be Chromium issue and has nothing to do with ungoogled-chromium.

**Comment by matsushita1918** [comment]
So I did run normal chrome, it has the same critical error as ungoogled, the stock version of Chrome did score slightly worse and the test did take longer than your version, it's scores were 355 passed, 26 warnings, 1 critical error and 22 skipped, would it be possible to update it to get rid of that critical error all it says besides what I sent above which is the same was cookie set by Java script should not be sent over http. Only way to see everything it picks up is if you run it yourself due to the fact it shows your  ip so you can go back and view your individual test scores anytime. It does about 500 tests with detailed descriptions of each.

**Comment by matsushita1918** [comment]
you can also set it to not remember your score Reporting your test results allows you (and only you) to review them later, and allows us to improve BrowserAudit's performance and design more effective tests. We'll store your test results, along with your IP address and web browser's User-Agent string. We do not collect any personally-identifying information or share your individual test results with anyone else., you can have it set to not remember it, but then you can't send the link to anyone. At the bottom of the page it says other settings which is a drop down menu

**Comment by PF4Public** [comment]
I doubt we can fix this Chromium issue. At best you could report this issue to Chromium developers.

**Comment by matsushita1918** [comment]
I really appreciate you taking the time to help out, keep up the good work on this fork of chrome, it'll be a life saver if FF goes down one day especially. I'd say chrome ungoogled and FF are pretty much the last two good browsers.

**Comment by irfannfl** [comment]
i think the test method is flawed, i run the script and see the request in network monitor and it's https instead of http, i think it because chrome force use https even if http specified. so nothing critical actually happen, the cookie is sent because it's in https.

**Comment by PF4Public** [comment]
@irfannfl Thank you for thorough testing! Shame on me I didn't test it meticulous enough :(

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
