### ISSUE TITLE
When no one wants to help, the topic loses its meaning!

### ISSUE THREAD

**Issue by Rusenche** [ungoogled-software/ungoogled-chromium-windows#244]
**_When no one wants to help, the topic loses its meaning!**

**Comment by PF4Public** [comment]
One needs to provide a translate URL for this to work. See https://github.com/ungoogled-software/ungoogled-chromium/pull/1175

**Comment by Rusenche** [comment]
I looked at the reference you wrote.

But I really don't understand. Can you be a bit more clear as for a complete beginner?!

I have no idea what to do with "--translate-script-url" - there is clearly no such flag.

I open this site: http://www.baidu.com/ and I want to translate it, for example, into Spanish, German, but the "Translate to" menu does not appear. This is my question and the uncertainty of how to make this "Translate to" menu appear for me with your help?!

Who knows how many others like me don't even know that this translation feature is already available, but we don't know how to activate and use it.

Thanks.

**Comment by Rusenche** [comment]
Too bad no one wants to help...

**Comment by Rusenche** [comment]
It goes without saying that the activation of the google translator from its settings = pointless activation, because there will be no translation. The function is blocked and no one wants to explain it in simple terms, which is unacceptable when asking a question asking for help. Worse is when instead of help there is no one on the other side, and this nowadays demonstrates that society is demoralized and lacks values.

**Comment by ansoni-san** [comment]
You could simply install an extension for this.

**Comment by ansoni-san** [comment]
That's not very helpful for others, changing the topic 🤦🏽‍♂️

Can someone close this then?
