### ISSUE TITLE
changes for chromium.ico fail to take effect

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#250]
I have modified all possible PNG, SVG, ICO and more files containing the chromium logo and it refuses to change the application icon, does anyone know why, or the direct file path causing this? basically I've modified all chromium.ico files (works in chromium) and they fail to take effect.

**Comment by 0xGingi** [comment]
You can take a look at my python rebrand script to see how I do it

https://github.com/0xGingi/0xgingi-browser/tree/main/rebrand

**Comment by infinitegame111** [comment]
ok thanks

**Comment by infinitegame111** [comment]
What script do I run? I see tons of icons and logos.

**Comment by 0xGingi** [comment]
script.py is the main rebrand script, config.py has all the icon/logo locations

**Comment by infinitegame111** [comment]
so run both?

**Comment by 0xGingi** [comment]
yeah, modify the script.py to your src location/rebrand name, replace the icons with yours, then run config.py then run script.py

**Comment by infinitegame111** [comment]
it just modifying all the Icons? I already did that all these are modified it just won't show the logo.
The dock/app icon is chrome but everything else is mine

**Comment by 0xGingi** [comment]
Exactly which application icon isn't changing for you?

**Comment by infinitegame111** [comment]
everyone but the applciation icon being when you search for Undone (my browser) it's renamed and everything just won't change the icon every every icon is changed but the dock icon, the app icon all possible chromium.ico files are changed.

**Comment by 0xGingi** [comment]
Do you mean like this? It could either be some windows caching issue then maybe? 

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/104647854/49384737-164b-4f8f-ab73-464fa5df6aa1)

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/104647854/12f1664d-62bd-4f09-bcf1-f278ecfdf501)

**Comment by infinitegame111** [comment]
yes

**Comment by infinitegame111** [comment]
the only icon error

**Comment by 0xGingi** [comment]
Dumb question, but have you rebooted since changing the icon?

**Comment by infinitegame111** [comment]
I have many times and you can search my code all chromium.ico files are modified

**Comment by 0xGingi** [comment]
Hmm interesting, you can take a look at how I do my replacements on my repo and see if that works better for you. I split the build.py into 2 scripts. The first part downloads chromium and runs the patch files, then the 2nd script does the building, I run the rebrand script and other file replacements in between the 2.

**Comment by PF4Public** [comment]
This issue tracker is for reporting issues for ungoogled-chromium-windows.
