### ISSUE TITLE
`ClearDataOnExit` feature flag doesn't work as intended

### ISSUE THREAD

**Issue by SwipeL1** [ungoogled-software/ungoogled-chromium-windows#259]
**Version**
Version 116.0.5845.82 (Official Build, ungoogled-chromium) (64-bit)

**Describe the bug**
Closing and reopening the browser does not clear browsing data, even if the `ClearDataOnExit` flag is enabled.

**How to Reproduce?**
Under `chrome://flags`, enable the `#clear-data-on-exit` feature flag. Restart the browser. Browse the Internet for a short time, then close and reopen the browser.

![thing](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/95476190/e7e95666-11e4-4c22-b179-58002394a873)

**Actual behavior**
The browsing data doesn't get cleared.

**Expected behavior**
The browsing data should get cleared.

**Additional context**
_No response_

**Comment by Nifury** [comment]
https://github.com/ungoogled-software/ungoogled-chromium/blob/2d25d5312e923d4e0ffa7de178358e9a4984d3da/patches/extra/ungoogled-chromium/add-flag-to-clear-data-on-exit.patch#L37-L42

Basically `data_types.empty()` returns true and no browsing data is cleared. 
No idea why.

**Comment by teeminus** [comment]
Maybe @Ahrotahn has an idea?

**Comment by Ahrotahn** [comment]
Sorry for the late response, I just got back from a trip.  I'll take a look into this over the coming days.

**Comment by PF4Public** [comment]
Should be fixed in 117
