### ISSUE TITLE
Fails to connect to Discord VCs

### ISSUE THREAD

**Issue by SheepCommander** [ungoogled-software/ungoogled-chromium-windows#263]
I prefer using discord in browser since the app is just a glorified website, but for some reason the Ungoogled Chromium browser gets stuck on the "RTC Connecting" step and does not change

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/66646514/e37e89af-6320-46d2-b88f-2f3279435901)
(Discord does not send my voice packets nor receive others voices)

---
For comparison, Edge still works
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/66646514/47edfc2c-a971-4d88-ad84-7ecc894e3fb9)

**Comment by SheepCommander** [comment]
I have no knowledge of how to help diagnose the problem but I do know a much older binary worked before I upgraded recently

**Comment by Nifury** [comment]
WebRTC is disabled by default by [winchrome](https://github.com/macchrome/winchrome)

**Comment by SheepCommander** [comment]
tysm, I thought it might be something like that but I was too dumb to really know what the list of flags on the wiki meant

Sorry for non-issue ;-;

**Comment by SheepCommander** [comment]
> WebRTC is disabled by default by [winchrome](https://github.com/macchrome/winchrome)
> 
> chrome://settings/content/webrtc

Actually nothing shows up when I go to chrome://settings/content/webrtc , I'm on the latest release from this repository not winchrome is that okay?

**Comment by Nifury** [comment]
Hmmm Discord and WebRTC work fine on my end, so I'm assuming you are using the build from the winchrome repo. 

Maybe the DevTools console could provide some hints about why Discord fails to connect.

**Comment by SheepCommander** [comment]
(Oops sorry for deleting my comment)

I ended up just downloading the latest release from Winchrome and now it works. Before I was using the latest release from ungoogled-chromium-windows, which has RTC disabled but does not have a `chrome://settings/content/webrtc` page.

**Comment by Nifury** [comment]
Ah you are right. WebRTC is indeed disabled by default: https://github.com/ungoogled-software/ungoogled-chromium/pull/2359
Can be re-enabled via chrome://flags/#webrtc-ip-handling-policy
I forgot I changed the default setting 😂


So I'll go ahead and close this issue now that Discord works.
