### ISSUE TITLE
non-existent domain throw `ERR_INTERNET_DISCONNECTED` on ungoogled-chromium = 118

### ISSUE THREAD

**Issue by delhi2050** [ungoogled-software/ungoogled-chromium-windows#276]
it should be `ERR_NAME_NOT_RESOLVED` or `DNS_PROBE_FINISHED_NXDOMAIN`

* v118 secure DNS **(off)** -> **ERR_INTERNET_DISCONNECTED**
* v118 secure DNS **(on)** -> ERR_NAME_NOT_RESOLVED
* v117 secure DNS **(off)** -> DNS_PROBE_FINISHED_NXDOMAIN
* v117 secure DNS **(on)** -> ERR_NAME_NOT_RESOLVED

**Comment by PF4Public** [comment]
Have you tried vanilla Chromium?

**Comment by PF4Public** [comment]
What is your exact version of ungoogled-chromium?
