### ISSUE TITLE
Error Build 119

### ISSUE THREAD

**Issue by sevenloveomg** [ungoogled-software/ungoogled-chromium-windows#282]
I has error when build 28k file
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/70572291/e1a4421c-bed2-4214-bdc7-de386d63c359)

How to fix it?

**Comment by Nifury** [comment]
Python is probably not configured properly. 
There is a section in readme regarding turning off the app execution aliases.
https://stackoverflow.com/questions/57485491/python-python3-executes-in-command-prompt-but-does-not-run-correctly

**Comment by sevenloveomg** [comment]
I'm reinstall python 3.9 and resolved this error. Thank [Nifury](https://github.com/Nifury)
