### ISSUE TITLE
Leak local IP webrtc

### ISSUE THREAD

**Issue by sevenloveomg** [ungoogled-software/ungoogled-chromium-windows#286]
resolved

**Comment by cuongnv02101994** [comment]
Problem with WEBRTC:
Leak IPlocal all version ungoogle
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/70572291/b4f93a76-ee6f-4bd6-b0e3-78407d65cfe5)

**Comment by PF4Public** [comment]
1. No issue with webgl, it is intended to be so.

2. Have you changed chrome://flags/#enable-webrtc-hide-local-ips-with-mdns and/or chrome://flags/#webrtc-ip-handling-policy?

**Comment by sevenloveomg** [comment]
> 1. No issue with webgl, it is intended to be so.
> 2. Have you changed chrome://flags/#enable-webrtc-hide-local-ips-with-mdns and/or chrome://flags/#webrtc-ip-handling-policy?

this is default after build. but I'm use --webrtc-ip-handling-policy=default_public_interface_only to resolved this.
