### ISSUE TITLE
Problem add extension

### ISSUE THREAD

**Issue by sevenloveomg** [ungoogled-software/ungoogled-chromium-windows#291]
I tried add some extension to chromium. But I'm see problem "**Item currently unavailable. Please check the troubleshooting guide.**"

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/70572291/1ec4e6da-8d11-491f-8429-fea5a56b2ed7)

What can I do?

**Comment by teeminus** [comment]
You cannot install extensions directly from the chrome webstore. Please refer to the ungoogled-chromium wiki for more information: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore
