### ISSUE TITLE
Gridinsoft detects ( Trojan.Heur!.02012822 ) on chrome.dll - version 119.0.6045.160 !

### ISSUE THREAD

**Issue by SteveJobsCousin** [ungoogled-software/ungoogled-chromium-windows#296]
i tested both " **chrome.dll** " from (google chrome) vs ( ungoogled-chromium-window ) on virustotal.com

- file hash : `18e5a31330f758001b88872f0d6870f819e89da0e947a32a8c08ed429aaf779c`

and only ( ungoogled-chromium-window  -> **chrome.dll** ) have shown a result of **( Trojan.Heur!.02012822 )**

despite if it a false positive or not ,   i'm trying to understand what really causes this, what code did we change to trigger it, and how we can fix it ?!

**Comment by teeminus** [comment]
I'm sorry, but there is no official .160 release of ungoogled-chromium-windows. The latest release is 119.0.6045.159-1.1.

You seem to be using an unofficial version of ungoogled-chromium-windows that was released outside of the ungoogled-chromium organization and we do not provide support for those.

**Comment by SteveJobsCousin** [comment]
@teeminus , yeah i meant 119.0.6045.159-1.1_windows , it was ( miss copy-past of the name ) on the wrong folder name .

**Comment by SteveJobsCousin** [comment]
> I'm sorry, but there is no official .160 release of ungoogled-chromium-windows. The latest release is 119.0.6045.159-1.1.
> 
> You seem to be using an unofficial version of ungoogled-chromium-windows that was released outside of the ungoogled-chromium organization and we do not provide support for those.

it was ( miss copy-past of the name ) on the wrong folder name .
i meant ungoogled-chromium 119.0.6045.159-1.1_windows .

you can check that by yourself drop "chrome.dll" on virustotal.com and see the result .

**Comment by Nifury** [comment]
The lack of a valid digital certificate is most likely the reason. 
If you strip the digital certificate from google chrome, I believe it will be reported as virus as well.
