### ISSUE TITLE
git clone Filename too long

### ISSUE THREAD

**Issue by Jurrer** [ungoogled-software/ungoogled-chromium-windows#303]
While building latest `120.0.6099.109` I encountered this error:

Cloning into 'build\src'...
remote: Finding sources: 100% (433407/433407)
remote: Total 433407 (delta 93458), reused 276340 (delta 93458)
Receiving objects: 100% (433407/433407), 1.19 GiB | 11.54 MiB/s, done.
Resolving deltas: 100% (93458/93458), done.
error: unable to create file third_party/blink/web_tests/virtual/async-script-scheduling-finished-parsing-with-dom-content-loaded-wait-for-async-script/wpt_internal/async-script-scheduling/execution-order.sub_default-expected.txt: Filename too long

I have LongPathsEnabled, but I don't that's related
Quick search, and [this seems to fix it](https://stackoverflow.com/a/52699496).  
`git config --system core.longpaths true`

I suggest adding this to README build requirements.

Edit: I don't think it's a problem with MAX_PATH env. I have it set according to README

**Comment by networkException** [comment]
I believe this is already part of the readme?

> Make sure to lift the MAX_PATH length restriction, either by clicking the button at the end of the Python installer or by [following these instructions](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#:~:text=Enable,Later).

**Comment by FriedGenera** [comment]
Yep I had the same error when I first tried to build, I can confirm that `LongPathsEnabled` at 1 doesn't seem to do anything for this problem, I just moved the whole folder to a place where it would have a shorter path.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
