### ISSUE TITLE
SetIpv6ProbeFalse flag cause false ipv4 dns result (172.xx.xx.xx) return for local network computer

### ISSUE THREAD

**Issue by Brbrbr1995** [ungoogled-software/ungoogled-chromium-windows#310]
test in chrome://net-internals/?#dns
result look like this:
```
DNS lookup
Input a domain name to look up:

Domain: 
example.com
 
Resolved IP addresses of "XXXXX-pc": ["172.XX.XX.XX","192.168.1.XX"].
No alternative endpoints.
Host resolver cache Clear host cache
```

**Comment by PF4Public** [comment]
Please provide more information so that we could better understand your problem.

**Comment by Brbrbr1995** [comment]
SetIpv6ProbeFalse flag ENABLE:
![en](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/150146865/9018cc6b-3bca-4049-9c60-ccda5b22c2b3)

DISABLE:
![dis](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/150146865/6de96415-f23e-4df8-9c49-55ce032c72de)

**Comment by Brbrbr1995** [comment]
this caused some webpage hosted on local network fail to load

**Comment by PF4Public** [comment]
172.16.0.0/12 is a reserved network for local allocation. Enabling `SetIpv6ProbeFalse` forces it to use only IPv4 addresses, which would resolve both IP for your host. It is not an issue of ungoogled-chromium if your network also uses IP addresses from that range.
