### ISSUE TITLE
UI is different to google chrome

### ISSUE THREAD

**Issue by B1ack3ye** [ungoogled-software/ungoogled-chromium-windows#316]
Why is the UI so different from Google Chrome? I roughly tried to copy the UI (apart from the colors), but it seems that the size of the icons (back and forth) and the general height etc. do not match that of Google Chrome.

The font and the color of the font do not match either.

The spacing of the bookmarks doesn't fit either, either I'm missing a setting or it's something else.

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/63259739/926f3229-1f04-432d-bf85-2d4f0db3fd76)

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/63259739/3c82c746-e218-4179-9342-7723ddd6a0e5)

**Comment by networkException** [comment]
This seems to be mostly part of the [Chrome Refresh 2023](https://blog.google/products/chrome/Google-chrome-new-features-redesign-2023/) which is not enabled by default in Chromium. You can enable it here: chrome://flags/#chrome-refresh-2023

**Comment by B1ack3ye** [comment]
Ahh I see the error, I only had "Chrome WebUI Refresh 2023" enabled.

Thanks for the quick help.

**Comment by B1ack3ye** [comment]
I just found out something that might help other people with this problem;

If you disable the sidebar under the flags, the Chrome Refresh 2023 will no longer load.

Flag: [#customize-chrome-side-panel](chrome://flags/#customize-chrome-side-panel)

This is the 2nd option under the experimental features button.
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/63259739/4c237423-3b60-48bb-ab4a-fab669db6b32)

Sorry if it is on German, can't change it to English ;D

With the sidebar enabled: ![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/63259739/97bbab80-4b9b-4b36-b7ae-b4a6a1f418dd)

Sidebar disabled: ![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/63259739/750941a6-4810-40fb-927f-a05634353d68)
