### ISSUE TITLE
Usage of policies blocks usage of Secure DNS (DoH)

### ISSUE THREAD

**Issue by fossfreak** [ungoogled-software/ungoogled-chromium-windows#319]
This is still an issue:
_Originally posted by @PF4Public in https://github.com/ungoogled-software/ungoogled-chromium/issues/2195#issuecomment-1585843152_

Setting Secure DNS via policy seems to work at first glance:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium]
"DnsOverHttpsMode"="secure"
"DnsOverHttpsTemplates"="https://dns.quad9.net/dns-query{?dns}"
``` 
![Zwischenablage-1](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/134852899/75fa0f5f-73ef-4266-90fc-e3961c2bc5b4)

Actually the policy setting is not respected. DNS-resolution is still done by System-DNS.

**Comment by PF4Public** [comment]
Do you need a system policy specifically?
