### ISSUE TITLE
122 version not save cookie google 

### ISSUE THREAD

**Issue by vnzlogin** [ungoogled-software/ungoogled-chromium-windows#323]
I run ungoogled windows by cmd: chrome.exe --disable-encryption --disable-machine-id --user-data-dir="C:\Users\PHV-01\Desktop\test2
Then, i login google account success. But, when i reopen browser, it not save cookie account google, i must login again.
Help me and fix it

**Comment by PF4Public** [comment]
Please consider reading [the FAQ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq).
