### ISSUE TITLE
Problems with build on Windows 10 x64

### ISSUE THREAD

**Issue by zhouwenkun** [ungoogled-software/ungoogled-chromium-windows#33]
**1.AttributeError: 'NoneType' object has no attribute 'strip'(my python-2 version is 2.7.9)**
D:\ungoogled-chromium-windows>py build.py
Python 3.6.8
Traceback (most recent call last):
  File "build.py", line 210, in <module>
    main()
  File "build.py", line 127, in main
    _test_python2(parser.error)
  File "build.py", line 86, in _test_python2
    result.stdout.strip()))
AttributeError: 'NoneType' object has no attribute 'strip'
**finally, i comment the method '_test_python2' line at 127 in build.py, so it will skip python-2 test.**

**2.next, i encounter this unknown problem!. so i need my guys help! thanks!!!**
INFO: * Applying flag-fingerprinting-canvas-image-data-noise.patch (85/85)
patching file chrome/browser/about_flags.cc
patching file content/browser/renderer_host/render_process_host_impl.cc
patching file content/child/runtime_features.cc
patching file third_party/blink/public/platform/web_runtime_features.h
patching file third_party/blink/renderer/platform/BUILD.gn
patching file third_party/blink/renderer/platform/exported/web_runtime_features.cc
patching file third_party/blink/renderer/platform/graphics/image_data_buffer.cc
patching file third_party/blink/renderer/platform/graphics/static_bitmap_image.cc
patching file third_party/blink/renderer/platform/graphics/static_bitmap_image.h
patching file third_party/blink/renderer/platform/runtime_enabled_features.json5
INFO: * Applying chromium-skia-harmony.patch (1/16)
patching file third_party/skia/src/ports/SkFontHost_FreeType.cpp
INFO: * Applying fix-cfi-failures-with-unbundled-libxml.patch (2/16)
patching file third_party/blink/renderer/core/xml/parser/xml_document_parser.cc
Hunk #1 succeeded at 137 (offset -2 lines).
Hunk #2 succeeded at 156 (offset -2 lines).
Hunk #3 succeeded at 203 (offset -2 lines).
Hunk #4 succeeded at 279 (offset -2 lines).
patching file third_party/blink/renderer/core/xml/xsl_style_sheet_libxslt.cc
patching file third_party/blink/renderer/core/xml/xslt_extensions.cc
patching file third_party/blink/renderer/core/xml/xslt_processor_libxslt.cc
patching file third_party/blink/renderer/core/xml/xslt_unicode_sort.cc
patching file third_party/libxml/chromium/libxml_utils.cc
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file third_party/libxml/chromium/libxml_utils.cc.rej
Traceback (most recent call last):
  File "build.py", line 210, in <module>
    main()
  File "build.py", line 175, in main
    source_tree
  File "D:\ungoogled-chromium-windows\ungoogled-chromium\utils\patches.py", line 54, in apply_patches
    subprocess.run(cmd, check=True)
  File "X:\zhouwenkun\Python36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\ungoogled-chromium-windows\\build\\src\\third_party\\git\\usr\\bin\\patch.exe', '-p1', '--ignore-whitespace', '-i', 'D:\\ungoogled-chromium-windows\\patches\\inox-patchset\\fix-cfi-failures-with-unbundled-libxml.patch', '-d', 'D:\\ungoogled-chromium-windows\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.

**Comment by tangalbert919** [comment]
1. Please update Python 2 on your computer.

2. I cannot reproduce this error on my Win10 machine. Did you make any modifications on your end before you started building?

**Comment by zhouwenkun** [comment]
> 1. Please update Python 2 on your computer.
> 2. I cannot reproduce this error on my Win10 machine. Did you make any modifications on your end before you started building?

**Comment by zhouwenkun** [comment]
> 1. Please update Python 2 on your computer.
> 2. I cannot reproduce this error on my Win10 machine. Did you make any modifications on your end before you started building?

**Thanks! now, i think it is important to solve is the problem1.below is my test,but not expect! so i want to know how to config python2 and python3 enviroment variable the same time in path detaily.**
forgive my poor english!!! haha! thanks guys!
![image](https://user-images.githubusercontent.com/7598989/75651484-859f9f00-5c93-11ea-8d3c-5e1521f30961.png)
