### ISSUE TITLE
2 problems for bookmarks

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#333]
1. ugly font for bookmarks in Chinese
2. toggle "bookmarks bar" not always work (not always reproducable)

**Comment by playgithub** [comment]
a new version is on building now

**Comment by playgithub** [comment]
a new version is on building now

**Comment by Nifury** [comment]
Same issue in chrome. 
Will probably be fixed in 124. 
https://www.theverge.com/2024/3/25/24111273/microsoft-google-chrome-text-rendering-improvements

**Comment by playgithub** [comment]
The font problem haven't been solved in the most recent version 123.0.6312.86-1.1
Wait for version 124
