### ISSUE TITLE
NextDNS provider is not available.

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-windows#336]
It was available on Linux.

**Comment by Nifury** [comment]
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/7867461/d59d1b0b-5199-4423-912f-4d6a6faa5555)

It is available. What is your Chromium version and where did you get the installer file?

**Comment by tomasz1986** [comment]
Just for the record, I also don't see it here, running the same official Windows version.

**Comment by Nifury** [comment]
I just ran the same version in Windows Sandbox and NextDNS was right there. 

Maybe a new and empty profile will make it appear again.

**Comment by tomasz1986** [comment]
Maybe it is location or locale-dependent? For example, this is the case when it comes to the default list of search engines, which changes depending on the OS language and possibly your location. Just a guess, as I haven't looked into the actual source code though.

**Comment by Nifury** [comment]
> Maybe it is location or locale-dependent? For example, this is the case when it comes to the default list of search engines, which changes depending on the OS language and possibly your location. Just a guess, as I haven't looked into the actual source code though.

I was about to say that!
It seems it is only available in the US. 
```
      new DohProviderEntry(
          "NextDns",
          MAKE_BASE_FEATURE_WITH_STATIC_STORAGE(
              DohProviderNextDns, base::FEATURE_ENABLED_BY_DEFAULT),
          /*dns_over_53_server_ip_strs=*/{},
          /*dns_over_tls_hostnames=*/{}, "https://chromium.dns.nextdns.io",
          /*ui_name=*/"NextDNS",
          /*privacy_policy=*/"https://nextdns.io/privacy",
          /*display_globally=*/false, /*display_countries=*/{"US"},
          LoggingLevel::kNormal),
```
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/dns/public/doh_provider_entry.cc#214
