### ISSUE TITLE
how can i rename the chromium process name in task manager!

### ISSUE THREAD

**Issue by zhouwenkun** [ungoogled-software/ungoogled-chromium-windows#35]

**Comment by tangalbert919** [comment]
How, exactly, is this an issue?

**Comment by zhouwenkun** [comment]
@tangalbert919  I mean that how i can modify the process name of the browser application(chromium).

**Comment by Eloston** [comment]
I think you'll need to change the source code in order to do that. There are several other Chromium forks that do this; you should be able to apply their patch and rebuild the browser yourself.
