### ISSUE TITLE
The latest version cannot turn off the 2023 UI at all.

### ISSUE THREAD

**Issue by Arsiendle** [ungoogled-software/ungoogled-chromium-windows#350]
I really hate the UI of 2023 very much.,Originally, all the UI about 2023 in the previous version was useless.,Only by giving up the sidebar function and turning off the sidebar can you go back to the previous UI.,But the latest version doesn't seem to even be able to do this.

**Comment by PF4Public** [comment]
What is this issue? Is it a bug or what?

**Comment by PF4Public** [comment]
I doubt we can do anything about that.
