### ISSUE TITLE
can't use the GitHub website

### ISSUE THREAD

**Issue by quazuo** [ungoogled-software/ungoogled-chromium-windows#358]
The GitHub website "crashes" (the Error screen shows up) when viewing branches and when viewing files in repositories. When I open a branch or any file in any repo, I see it for a split second and immediately get the Error screen. I've checked with other browsers and it happens only on Ungoogled Chromium. It also occurs in incognito mode, where I also have all my extensions disabled.

![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/25569500/82e8c7a2-ec9e-4ecf-8cac-94b540b4908a)

**Comment by Algiuxs** [comment]
can you send more info about the browser, site where you downloaded it from?

**Comment by PF4Public** [comment]
Please try latest version

**Comment by networkException** [comment]
Indeed this looks a lot like https://github.com/ungoogled-software/ungoogled-chromium/pull/2790. Please clarify if you're using a version that already includes this fix
