### ISSUE TITLE
`SetIpv6ProbeFalse` option not working as expected

### ISSUE THREAD

**Issue by delhi2050** [ungoogled-software/ungoogled-chromium-windows#371]
Regardless of whether it is set to enable or disable, IPv6 address are still detectable on test-ipv6.com or ipv6-test.com, and the default priority may still be IPv6.

**Comment by PF4Public** [comment]
This option isn't supposed to be somehow hiding your IP.

**Comment by PF4Public** [comment]
> even if this option doesn’t completely disable IPv6 in Chromium, it should resolve domain names to A records rather than AAAA records and connect to IPv4.

This option is intended to avoid calling google servers in order to determine whether IPv6 connectivity is available.
