### ISSUE TITLE
Home buttom missing

### ISSUE THREAD

**Issue by tipitao** [ungoogled-software/ungoogled-chromium-windows#381]
Hello, I have been using the application for several months, and it works correctly. When updating to the latest version (128.0.6613.119-1) from 127.0.6533.99 (this work fine) of Windows (X64) portable I noticed that the Home button no longer appeared (I have updated several times and never had the problem with the Home button). I went into the settings to activate it again but I saw that it was automatically deactivated again and that is why it does not appear. Is there any solution for this?

All the best

**Comment by alan1188** [comment]
fixed with 128.0.6613.137-1

**Comment by tipitao** [comment]
Ok thanks. I am runing this versin now and buton is enabled.

Regards
