### ISSUE TITLE
Can't load YouTube videos

### ISSUE THREAD

**Issue by r4ffa47** [ungoogled-software/ungoogled-chromium-windows#390]
I don't know why, but since the day before yesterday, YouTube doesn't work whenever I try to load a video. It's not an internet issue - I've already checked if it loads videos with another browser like Firefox and it works. It seems to be that, whenever I log in to my main account in ungoogled Chromium, it just doesn't load YouTube videos. Is anyone else having this issue?
![image](https://github.com/user-attachments/assets/a2898ae7-ff1e-434d-81c2-09725cf904b3)

**Comment by PF4Public** [comment]
Please continue in the core repo: https://github.com/ungoogled-software/ungoogled-chromium/issues/3012
