### ISSUE TITLE
Add default search engine manually other than provided

### ISSUE THREAD

**Issue by AllenAlien920** [ungoogled-software/ungoogled-chromium-windows#393]
How can I add new default search engines manually? I can't find the option anywhere.
![](https://github.com/user-attachments/assets/3561cc9e-3ffb-4c1a-83e3-f0402658b085)
![](https://github.com/user-attachments/assets/9f4e5855-4a0e-44ec-8359-7c9abc055168)

**Comment by tomasz1986** [comment]
The wording may be confusing, but it's right there in your screenshot.

![image](https://github.com/user-attachments/assets/f214179e-67af-47c7-91d0-9c7cb0519958)

**Comment by AllenAlien920** [comment]
Sorry for the confusion, what I meant is when I enter something (not a URL) in the address bar, I want it to redirect to Google automatically to search the words I entered, but Google isn't in the list, I can only choose from the search engines provided above, and I can't add manually.
![](https://github.com/user-attachments/assets/b0e1706c-9dd7-476a-8154-a8a180ba991b)

**Comment by tomasz1986** [comment]
You need to add Google manually (e.g. see https://github.com/ungoogled-software/ungoogled-chromium/issues/2730#issuecomment-1962999647).

**Comment by AllenAlien920** [comment]
Sorry
