### ISSUE TITLE
AMR Windows version

### ISSUE THREAD

**Issue by miguelgargallo** [ungoogled-software/ungoogled-chromium-windows#400]
### OS/Platform

Windows

### Installed

OS/Platform's package manager

### Version

latest

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [x] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [x] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [x] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

AMR Windows version

### How to Reproduce?

AMR Windows version

### Actual behaviour

AMR Windows version

### Expected behaviour

AMR Windows version

### Relevant log output

```sh
AMR Windows version
```

### Additional context

AMR Windows version

**Comment by PF4Public** [comment]
> AMR Windows version

Please add more details as to what your bug is. Is it a feature request instead?

**Comment by tomasz1986** [comment]
I assume they mean "ARM" as in ARM CPU architecture 😅.

**Comment by miguelgargallo** [comment]
Yes but there is an already, so I close the ticket
