### ISSUE TITLE
bug in current clang version

### ISSUE THREAD

**Issue by Luka-Filipovic** [ungoogled-software/ungoogled-chromium-windows#47]
@mdusome I had it as well. The problem is in the current clang version. I've fixed it by manually downloading newer clang from [here](https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-n353803-99ac9ce7-1.tgz). Unpack & overwrite everything in src/third_party\llvm-build\Release+Asserts\. And you can continue your build.

I'm not sure where can I find a packed new clang and llvm to include it in downloads.ini, so this solution can work for now.

_Originally posted by @Luka-Filipovic in https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/46#issuecomment-664973289_

**Comment by Eloston** [comment]
Solved with 84 release
