### ISSUE TITLE
Cannot open include file: 'stddef.h': No such file or directory

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#51]
VS2019 community
Windows 10 SDK 10.0.19041.0

```
fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
```

What is the problem?

**Comment by VioletGiraffe** [comment]
I managed to fix it by installing the latest Windows 11 SDK, but that still doesn't explain how other C and C++ ports managed to compile. All the necessary files were present, it was only a problem with includepath not being set to what it should be.
