### ISSUE TITLE
[Build problem] Build.py says no module downloads found

### ISSUE THREAD

**Issue by Oymate** [ungoogled-software/ungoogled-chromium-windows#56]
```
$ py build.py
Python 3.7.4
Traceback (most recent call last):
  File "build.py", line 220, in <module>
    main()
  File "build.py", line 134, in main
    _test_python2(parser.error)
  File "build.py", line 87, in _test_python2
    result.stdout.strip()))
AttributeError: 'NoneType' object has no attribute 'strip'


```

**Comment by tangalbert919** [comment]
Do you have Python 2 installed and added to PATH? That is required for building ungoogled-chromium.

**Comment by Oymate** [comment]
@tangalbert919 i have py2 here, but not sure about path anyway, I finally figured out how to install extension but please give at least a guide.

**Comment by yakagami** [comment]
@Oymate can you explain what you did to solve it? I am having the same issue.

**Comment by Oymate** [comment]
@yakagami sadly I didn't and advise you to use a virtual box with the latest ubuntu release and follow the build instruction.
