### ISSUE TITLE
Automating the process

### ISSUE THREAD

**Issue by Legedith** [ungoogled-software/ungoogled-chromium-windows#6]
Is it possible to automate the process? If yes, Then:
1. How do I precede with it.
2. What skill set do i need.
3. Where can I learn how to do so.

I am asking because someone told me that the process is really simple and not really hard, but time consuming. 
Well, time is all I have.

**Comment by Eloston** [comment]
Automating which process? Setting up the environment? Updating patches? Building? The skills you need to do any one task can vary a bit. However, if you want to be helpful in general, these may help you:

* Similar question here (some information is a bit old, but it's still mostly relevant to this day): https://github.com/Eloston/ungoogled-chromium/issues/235
* ungoogled-chromium documentation:
    * https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md
    * https://github.com/Eloston/ungoogled-chromium/blob/master/docs/developing.md
    * https://github.com/Eloston/ungoogled-chromium/blob/master/docs/design.md
* Chromium documentation on chromium.org (start with the building documentation, then poke around from there.)

**Comment by Eloston** [comment]
Well 77 is out and this thread is quiet, so closing.
