### ISSUE TITLE
Bad default  patch (disables encryption of cookies, passwords, settings...)

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-windows#65]
This patch
`ungoogled-chromium-windows\patches\ungoogled-chromium\windows\windows-disable-encryption.patch`
will disables encryption of cookies, passwords, settings...

Why it is used by default?

**Comment by raisehero** [comment]
It's to allow of portability of chromium by passing --disable-encryption
Google Chrome is not portable by contrast and encryption in this case is considered a user hostile mechanism by locking you into the Google Account ecosystem.

please read the https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md first
It is not enabled by default unless you EXPLICITLY pass --disable-encryption
Please don't just sperg NO ENCRYPTION=BAD, @playgithub.
