### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by sunnysinghnitb** [ungoogled-software/ungoogled-chromium-windows#66]
D:\ungoogled-chromium-windows>py build.py
Python 3.7.7
Traceback (most recent call last):
File "build.py", line 220, in <module>
main()
File "build.py", line 134, in main
_test_python2(parser.error)
File "build.py", line 87, in _test_python2
result.stdout.strip()))
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by tangalbert919** [comment]
Make sure you have Python 2 installed and added to PATH, as stated in the README.md file.
