### ISSUE TITLE
Finish updating windows-fix-building-without-safebrowsing.patch

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-windows#8]
So, d2674a9204ba474b859fd2ddbcd820ad1455ea38 made `windows-fix-building-without-safebrowsing.patch` a bit of a mess.

The approach of these new changes is to remove as much of Safe Browsing as possible, so much so that the code doesn't even reference the `safe_browsing` namespace (in the C++ code). The idea is since Google's been the most progressive with Safe Browsing in Windows, stubbing out the code may not sufficient to create a stable and reliable browser (i.e. not only does it compile, it must also run with no crashes or data corruption). 
[safe_browsing_remaining_files.txt](https://github.com/ungoogled-software/ungoogled-chromium-windows/files/3638368/safe_browsing_remaining_files.txt) contains a list of files that may need modification in order to fulfill this goal (i.e. files that contain the strings `safe_browsing` or `safebrowsing`, case-insensitive). Maybe this idea is too progressive or maybe it won't be practical going forward; I'm not too sure at this point. What do you guys think?

Also, I was a bit overly aggressive when updating this patch, so some of these changes aren't necessary; notably changes that removed code guarded by the `#if (FULL_SAFE_BROWSING)` macro in C++, or `if (safe_browsing_mode != 0)` in GN (or some variant thereof). We also technically don't need to fix `unittest` or `browsertest` code since we aren't running tests, but we will eventually want to do this if we want to run unit tests on our changes in the future.

EDIT: There will probably be more issues that will need to be fixed during compiling, linking, and (unfortunately) runtime after finishing the changes here, unless we're really careful about these changes. Safe Browsing has become quite ingrained in the browser at this point.

**Comment by tangalbert919** [comment]
It seems weird that only Windows will be getting this rather large patch, but if I have time, I can take a look and see what I can do.

**Comment by Eloston** [comment]
@tangalbert919 Yeah. In addition to the reasoning above, I think that this patch could be useful for other platforms in the future for issues like https://github.com/Eloston/ungoogled-chromium/issues/568 and https://github.com/Eloston/ungoogled-chromium/issues/631. For now, we should probably wait a few versions to see if such a large patch is a good idea or not.

Thanks again for updating the patch BTW, closing.
