### ISSUE TITLE
Would you use the builds I build?

### ISSUE THREAD

**Issue by TontyTon** [ungoogled-software/ungoogled-chromium-windows#90]
@Eloston Hey, as tangelbert919 is not building for now, I thought if I could. So, would you publish my builds?

I am not experienced, I will just follow instructions from Readme file, and test if the build is working or not.

**Comment by spslabo** [comment]
I for one would welcome some up-to-date Windows binaries, I think you should be fine if you just follow the binaries publishing process outlined here: https://github.com/ungoogled-software/ungoogled-chromium-binaries#publishing-new-binaries

**Comment by wchen342** [comment]
@TontyTon Everyone started inexperience, including myself. If you can make the build work and you think you can devote some time to the project and keep doing it (in contrast to a one-shot effort), then I think @Eloston will happy to accept.

In the event you only wish to publish a single build, then [ungoogled-chromium-binaries](https://github.com/ungoogled-software/ungoogled-chromium-binaries) is the right place for uploading third-party builds.

**Comment by EkkiBrue** [comment]
I would love to see your build! I refuse all other brothers by now ;)

**Comment by Eloston** [comment]
@TontyTon Yes! We welcome anyone to publish binaries to ungoogled-chromium-binaries. Please follow the instructions that others have linked: https://github.com/ungoogled-software/ungoogled-chromium-binaries#publishing-new-binaries

**Comment by TontyTon** [comment]
Ok sure, will try. I didn't know that there is seperate repository for this.

**Comment by EkkiBrue** [comment]
Machrome seems to deliver some win binaries now:

[https://github.com/macchrome/winchrome/releases](https://github.com/macchrome/winchrome/releases
)
They can´t be found on [https://ungoogled-software.github.io/ungoogled-chromium-binaries/](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)
