### ISSUE TITLE
Chromium 92 update

### ISSUE THREAD

**Issue by Eshanepicfighter** [ungoogled-software/ungoogled-chromium-windows#91]
Windows is the only binary with a version significantly behind the current ungoogled-chromium version. Is there a reason that this is the case?

**Comment by brodybits** [comment]
It looks like an update stalled in PR #84. Is there anything we can do to help get this going again?

**Comment by wchen342** [comment]
You can try to build yourself and figure out then problems, and then push to the PR (or create a new one if the original one cannot be updated). I think we just lack someone who can keep windows updated regularly right now.

**Comment by Eshanepicfighter** [comment]
I tried to build it myself and it failed. The documentation on building isn't really that clear

**Comment by Eshanepicfighter** [comment]
I looked at PR #84 and I'm building without the safe browsing patch. I'll see if it works or not

**Comment by Nifury** [comment]
> You can try to build yourself and figure out then problems, and then push to the PR (or create a new one if the original one cannot be updated). I think we just lack someone who can keep windows updated regularly right now.

Might be a dumb question, but is there a way to update patch offsets automatically? 
Seems that most updates are trivial but require lots of time if they are done manually. 
https://github.com/Eloston/ungoogled-chromium/commit/a8033105b76b614598df33469b717aa75d4586f3#diff-f1be16a78115f65dfd2553a282c7b1c7b53c9898615a350cb8f6817370c93aa3L4817

**Comment by Eshanepicfighter** [comment]
I removed the safe browsing patched and opened it up. Seems everything works fine except a graphical bug with the menu. I don't know if this will work on other people's computers.

**Comment by Eshanepicfighter** [comment]
Weirdly enough the build string internally is 89 but in the settings --> about menu it says 92. Not sure which build number it is actually but it does has some Chromium 90 and 91 features

**Comment by Eshanepicfighter** [comment]
I tried to compile with chromium 91 instead of 92. Failed with the same error as PR #84. Don't know why it suddenly worked when using chromium 92.

**Comment by wchen342** [comment]
@Nifury On Linux we use `quilt` to manage such minor changes (and that is why there is a `series` file). I don't know whether you can use it on Windows, maybe try WSL.

@Eshanepicfighter The error goes away most likely because code changes between v91 and v92. The error in #84 is not complete but my guess is symbol missing when linking (the error doesn't look exactly the same like on Linux but I think that is what happened). That usually means one of the patches missed some function definitions or function calls that should be removed so the linker is referring to them but cannot find the functions.

**Comment by Eshanepicfighter** [comment]
@wchen342 Ok. The only functional way right now to get ungoogled-chromium 92 on windows is to remove the safe browsing patch which I would not like to do that but its required until somebody can open a pull request with the patch. Whoever has the know how please open a pull request
