### ISSUE TITLE
How to use chromium source code already downloaded using depot_tools and add patches to it?

### ISSUE THREAD

**Issue by navaneethkm004** [ungoogled-software/ungoogled-chromium-windows#94]
I have already downloaded chromium source code using depot_tools and i want to use that for this project. How can i do that without re downloading it in the process?

**Comment by playgithub** [comment]
* cahce folder path: ungoogled-chromium-windows\build\downloads_cache
* chromium source code path in the cache is, for example, `ungoogled-chromium-windows\build\downloads_cache\chromium-92.0.4515.159.tar.xz`.

If a file in the cache is hit, the build scripts will skip the downloading.
